In [ ]:
import time
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader, random_split, ConcatDataset
from torchvision import datasets, transforms

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

PyTorch version: 2.10.0+cu128
CUDA available: True
Device: cuda

In [ ]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
mnist_transform = transforms.ToTensor()
cifar_transform = transforms.ToTensor()

mnist_full_train = datasets.MNIST(root='./data', train=True, download=True, transform=mnist_transform)
mnist_test = datasets.MNIST(root='./data', train=False, download=True, transform=mnist_transform)

cifar_full_train = datasets.CIFAR10(root='./data', train=True, download=True, transform=cifar_transform)
cifar_test = datasets.CIFAR10(root='./data', train=False, download=True, transform=cifar_transform)

print("MNIST train size:", len(mnist_full_train))
print("MNIST test size:", len(mnist_test))
print("CIFAR train size:", len(cifar_full_train))
print("CIFAR test size:", len(cifar_test))

100%|██████████| 9.91M/9.91M [00:01<00:00, 5.07MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 132kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.26MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 9.19MB/s]
100%|██████████| 170M/170M [00:13<00:00, 12.4MB/s]

MNIST train size: 60000
MNIST test size: 10000
CIFAR train size: 50000
CIFAR test size: 10000

In [ ]:
mnist_train, mnist_val = random_split(mnist_full_train, [50000, 10000])
cifar_train, cifar_val = random_split(cifar_full_train, [45000, 5000])

print("MNIST train:", len(mnist_train), "val:", len(mnist_val))
print("CIFAR train:", len(cifar_train), "val:", len(cifar_val))

MNIST train: 50000 val: 10000
CIFAR train: 45000 val: 5000

In [ ]:
def make_loaders(train_dataset, val_dataset, test_dataset, batch_size):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_loader, val_loader, test_loader

In [ ]:
train_loader, val_loader, test_loader = make_loaders(mnist_train, mnist_val, mnist_test, batch_size=64)

images, labels = next(iter(train_loader))
print("MNIST batch image shape:", images.shape)
print("MNIST batch label shape:", labels.shape)

train_loader, val_loader, test_loader = make_loaders(cifar_train, cifar_val, cifar_test, batch_size=64)

images, labels = next(iter(train_loader))
print("CIFAR batch image shape:", images.shape)
print("CIFAR batch label shape:", labels.shape)

MNIST batch image shape: torch.Size([64, 1, 28, 28])
MNIST batch label shape: torch.Size([64])
CIFAR batch image shape: torch.Size([64, 3, 32, 32])
CIFAR batch label shape: torch.Size([64])

In [ ]:
class MLP(nn.Module):
    def __init__(self, input_size, hidden_layers, num_classes=10, dropout=0.2):
        super().__init__()

        layers = []
        prev_size = input_size

        for hidden_size in hidden_layers:
            layers.append(nn.Linear(prev_size, hidden_size))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_size = hidden_size

        layers.append(nn.Linear(prev_size, num_classes))

        self.network = nn.Sequential(*layers)

    def forward(self, x):
        x = x.view(x.size(0), -1)   # flatten image
        return self.network(x)

In [ ]:
mnist_mlp = MLP(input_size=784, hidden_layers=[128], dropout=0.2).to(device)
cifar_mlp = MLP(input_size=3072, hidden_layers=[512, 256, 128], dropout=0.5).to(device)

x_mnist = torch.randn(64, 1, 28, 28).to(device)
x_cifar = torch.randn(64, 3, 32, 32).to(device)

print("MNIST MLP output:", mnist_mlp(x_mnist).shape)
print("CIFAR MLP output:", cifar_mlp(x_cifar).shape)

MNIST MLP output: torch.Size([64, 10])
CIFAR MLP output: torch.Size([64, 10])

In [ ]:
class SimpleCNN(nn.Module):
    def __init__(self, in_channels, num_classes=10):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(in_channels, 8, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(8),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(8, 8, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(8),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        if in_channels == 1:   # MNIST: 28x28 -> 14x14 -> 7x7
            self.classifier = nn.Linear(8 * 7 * 7, num_classes)
        else:                  # CIFAR: 32x32 -> 16x16 -> 8x8
            self.classifier = nn.Linear(8 * 8 * 8, num_classes)

    def forward(self, x):
        x = self.features(x)
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x

In [ ]:
class EnhancedCNN(nn.Module):
    def __init__(self, in_channels, num_classes=10):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(in_channels, 16, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        if in_channels == 1:   # MNIST: 28 -> 14 -> 7 -> 3
            self.classifier = nn.Sequential(
                nn.Linear(64 * 3 * 3, 128),
                nn.ReLU(),
                nn.Linear(128, num_classes)
            )
        else:                  # CIFAR: 32 -> 16 -> 8 -> 4
            self.classifier = nn.Sequential(
                nn.Linear(64 * 4 * 4, 128),
                nn.ReLU(),
                nn.Linear(128, num_classes)
            )

    def forward(self, x):
        x = self.features(x)
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x

In [ ]:
mnist_simple = SimpleCNN(in_channels=1).to(device)
mnist_enhanced = EnhancedCNN(in_channels=1).to(device)

cifar_simple = SimpleCNN(in_channels=3).to(device)
cifar_enhanced = EnhancedCNN(in_channels=3).to(device)

x_mnist = torch.randn(64, 1, 28, 28).to(device)
x_cifar = torch.randn(64, 3, 32, 32).to(device)

print("MNIST SimpleCNN:", mnist_simple(x_mnist).shape)
print("MNIST EnhancedCNN:", mnist_enhanced(x_mnist).shape)
print("CIFAR SimpleCNN:", cifar_simple(x_cifar).shape)
print("CIFAR EnhancedCNN:", cifar_enhanced(x_cifar).shape)

MNIST SimpleCNN: torch.Size([64, 10])
MNIST EnhancedCNN: torch.Size([64, 10])
CIFAR SimpleCNN: torch.Size([64, 10])
CIFAR EnhancedCNN: torch.Size([64, 10])

In [ ]:
def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    avg_loss = total_loss / total
    acc = correct / total
    return avg_loss, acc

In [ ]:
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            total_loss += loss.item() * images.size(0)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    avg_loss = total_loss / total
    acc = correct / total
    return avg_loss, acc

In [ ]:
def train_model(model, train_loader, val_loader, optimizer, criterion, device, epochs=10, patience=3):
    best_val_acc = 0
    best_state = None
    history = []
    no_improve = 0

    start_time = time.time()

    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc
        })

        print(f"Epoch {epoch:02d} | Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = model.state_dict()
            no_improve = 0
        else:
            no_improve += 1

        if no_improve >= patience:
            print("Early stopping triggered.")
            break

    runtime = time.time() - start_time

    if best_state is not None:
        model.load_state_dict(best_state)

    return model, best_val_acc, runtime, history

In [ ]:
batch_size = 64
train_loader, val_loader, test_loader = make_loaders(mnist_train, mnist_val, mnist_test, batch_size)

model = MLP(input_size=784, hidden_layers=[128], dropout=0.2).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

model, best_val_acc, runtime, history = train_model(
    model, train_loader, val_loader, optimizer, criterion, device,
    epochs=5, patience=2
)

test_loss, test_acc = evaluate(model, test_loader, criterion, device)

print("Best Val Acc:", best_val_acc)
print("Test Acc:", test_acc)
print("Runtime:", runtime)

Epoch 01 | Train Acc: 0.8888 | Val Acc: 0.9353
Epoch 02 | Train Acc: 0.9428 | Val Acc: 0.9529
Epoch 03 | Train Acc: 0.9584 | Val Acc: 0.9579
Epoch 04 | Train Acc: 0.9643 | Val Acc: 0.9630
Epoch 05 | Train Acc: 0.9705 | Val Acc: 0.9671
Best Val Acc: 0.9671
Test Acc: 0.9731
Runtime: 39.70143485069275

In [ ]:
import pandas as pd

In [ ]:
MLP_ARCHITECTURES = {
    "shallow": [128],
    "medium": [512, 256, 128],
    "deep": [1024, 512, 256, 128, 64]
}

In [ ]:
mlp_configs = [
    {"lr": 0.01,   "batch_size": 64,  "optimizer": "SGD",  "dropout": 0.2},
    {"lr": 0.01,   "batch_size": 64,  "optimizer": "Adam", "dropout": 0.2},
    {"lr": 0.001,  "batch_size": 64,  "optimizer": "SGD",  "dropout": 0.2},
    {"lr": 0.001,  "batch_size": 64,  "optimizer": "Adam", "dropout": 0.2},
    {"lr": 0.0001, "batch_size": 64,  "optimizer": "Adam", "dropout": 0.2},
    {"lr": 0.001,  "batch_size": 32,  "optimizer": "Adam", "dropout": 0.2},
    {"lr": 0.001,  "batch_size": 128, "optimizer": "Adam", "dropout": 0.2},
    {"lr": 0.001,  "batch_size": 64,  "optimizer": "Adam", "dropout": 0.5},
    {"lr": 0.01,   "batch_size": 128, "optimizer": "SGD",  "dropout": 0.5},
    {"lr": 0.0001, "batch_size": 32,  "optimizer": "Adam", "dropout": 0.5},
]

len(mlp_configs)

10

In [ ]:
def get_optimizer(name, model, lr, weight_decay=0.0):
    if name == "SGD":
        return optim.SGD(model.parameters(), lr=lr, weight_decay=weight_decay)
    elif name == "Adam":
        return optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        raise ValueError(f"Unknown optimizer: {name}")

In [ ]:
def run_mlp_experiment(dataset_name, architecture_name, hidden_layers, config,
                       train_dataset, val_dataset, test_dataset,
                       epochs=10, patience=3):

    if dataset_name == "MNIST":
        input_size = 784
    elif dataset_name == "CIFAR10":
        input_size = 3072
    else:
        raise ValueError("dataset_name must be 'MNIST' or 'CIFAR10'")

    batch_size = config["batch_size"]
    train_loader, val_loader, test_loader = make_loaders(
        train_dataset, val_dataset, test_dataset, batch_size
    )

    model = MLP(
        input_size=input_size,
        hidden_layers=hidden_layers,
        dropout=config["dropout"]
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = get_optimizer(config["optimizer"], model, lr=config["lr"])

    model, best_val_acc, runtime, history = train_model(
        model, train_loader, val_loader, optimizer, criterion, device,
        epochs=epochs, patience=patience
    )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    result = {
        "dataset": dataset_name,
        "architecture": architecture_name,
        "hidden_layers": str(hidden_layers),
        "lr": config["lr"],
        "batch_size": config["batch_size"],
        "optimizer": config["optimizer"],
        "dropout": config["dropout"],
        "best_val_acc": best_val_acc,
        "test_acc": test_acc,
        "runtime_sec": runtime
    }

    return result, history

In [ ]:
def tune_mlp_architecture(dataset_name, architecture_name, hidden_layers,
                          train_dataset, val_dataset, test_dataset,
                          configs, epochs=10, patience=3):

    all_results = []
    best_result = None
    best_val_acc = -1

    for i, config in enumerate(configs, start=1):
        print("=" * 80)
        print(f"{dataset_name} | MLP-{architecture_name} | Config {i}/{len(configs)}")
        print(config)

        result, history = run_mlp_experiment(
            dataset_name=dataset_name,
            architecture_name=architecture_name,
            hidden_layers=hidden_layers,
            config=config,
            train_dataset=train_dataset,
            val_dataset=val_dataset,
            test_dataset=test_dataset,
            epochs=epochs,
            patience=patience
        )

        all_results.append(result)

        print("Best Val Acc:", round(result["best_val_acc"], 4))
        print("Test Acc:", round(result["test_acc"], 4))
        print("Runtime (sec):", round(result["runtime_sec"], 2))

        if result["best_val_acc"] > best_val_acc:
            best_val_acc = result["best_val_acc"]
            best_result = result

    df = pd.DataFrame(all_results).sort_values(by="best_val_acc", ascending=False).reset_index(drop=True)
    return df, best_result

In [ ]:
mnist_shallow_df, mnist_shallow_best = tune_mlp_architecture(
    dataset_name="MNIST",
    architecture_name="shallow",
    hidden_layers=MLP_ARCHITECTURES["shallow"],
    train_dataset=mnist_train,
    val_dataset=mnist_val,
    test_dataset=mnist_test,
    configs=mlp_configs,
    epochs=8,
    patience=2
)

================================================================================
MNIST | MLP-shallow | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.6597 | Val Acc: 0.8429
Epoch 02 | Train Acc: 0.8398 | Val Acc: 0.8776
Epoch 03 | Train Acc: 0.8695 | Val Acc: 0.8908
Epoch 04 | Train Acc: 0.8825 | Val Acc: 0.8970
Epoch 05 | Train Acc: 0.8903 | Val Acc: 0.9025
Epoch 06 | Train Acc: 0.8969 | Val Acc: 0.9082
Epoch 07 | Train Acc: 0.9036 | Val Acc: 0.9115
Epoch 08 | Train Acc: 0.9089 | Val Acc: 0.9158
Best Val Acc: 0.9158
Test Acc: 0.9239
Runtime (sec): 60.87
================================================================================
MNIST | MLP-shallow | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.9132 | Val Acc: 0.9555
Epoch 02 | Train Acc: 0.9427 | Val Acc: 0.9588
Epoch 03 | Train Acc: 0.9501 | Val Acc: 0.9594
Epoch 04 | Train Acc: 0.9541 | Val Acc: 0.9611
Epoch 05 | Train Acc: 0.9560 | Val Acc: 0.9613
Epoch 06 | Train Acc: 0.9585 | Val Acc: 0.9629
Epoch 07 | Train Acc: 0.9590 | Val Acc: 0.9625
Epoch 08 | Train Acc: 0.9627 | Val Acc: 0.9641
Best Val Acc: 0.9641
Test Acc: 0.9662
Runtime (sec): 62.47
================================================================================
MNIST | MLP-shallow | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2882 | Val Acc: 0.5587
Epoch 02 | Train Acc: 0.5760 | Val Acc: 0.6590
Epoch 03 | Train Acc: 0.6456 | Val Acc: 0.7004
Epoch 04 | Train Acc: 0.6857 | Val Acc: 0.7351
Epoch 05 | Train Acc: 0.7221 | Val Acc: 0.7727
Epoch 06 | Train Acc: 0.7487 | Val Acc: 0.7979
Epoch 07 | Train Acc: 0.7716 | Val Acc: 0.8158
Epoch 08 | Train Acc: 0.7878 | Val Acc: 0.8250
Best Val Acc: 0.825
Test Acc: 0.831
Runtime (sec): 61.15
================================================================================
MNIST | MLP-shallow | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8886 | Val Acc: 0.9362
Epoch 02 | Train Acc: 0.9443 | Val Acc: 0.9544
Epoch 03 | Train Acc: 0.9578 | Val Acc: 0.9613
Epoch 04 | Train Acc: 0.9648 | Val Acc: 0.9661
Epoch 05 | Train Acc: 0.9702 | Val Acc: 0.9663
Epoch 06 | Train Acc: 0.9729 | Val Acc: 0.9710
Epoch 07 | Train Acc: 0.9768 | Val Acc: 0.9714
Epoch 08 | Train Acc: 0.9791 | Val Acc: 0.9718
Best Val Acc: 0.9718
Test Acc: 0.9765
Runtime (sec): 62.99
================================================================================
MNIST | MLP-shallow | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.7817 | Val Acc: 0.8811
Epoch 02 | Train Acc: 0.8806 | Val Acc: 0.9008
Epoch 03 | Train Acc: 0.8992 | Val Acc: 0.9088
Epoch 04 | Train Acc: 0.9105 | Val Acc: 0.9161
Epoch 05 | Train Acc: 0.9168 | Val Acc: 0.9215
Epoch 06 | Train Acc: 0.9220 | Val Acc: 0.9267
Epoch 07 | Train Acc: 0.9300 | Val Acc: 0.9313
Epoch 08 | Train Acc: 0.9323 | Val Acc: 0.9358
Best Val Acc: 0.9358
Test Acc: 0.9404
Runtime (sec): 62.46
================================================================================
MNIST | MLP-shallow | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.9036 | Val Acc: 0.9442
Epoch 02 | Train Acc: 0.9516 | Val Acc: 0.9572
Epoch 03 | Train Acc: 0.9635 | Val Acc: 0.9641
Epoch 04 | Train Acc: 0.9698 | Val Acc: 0.9699
Epoch 05 | Train Acc: 0.9739 | Val Acc: 0.9710
Epoch 06 | Train Acc: 0.9780 | Val Acc: 0.9712
Epoch 07 | Train Acc: 0.9798 | Val Acc: 0.9724
Epoch 08 | Train Acc: 0.9816 | Val Acc: 0.9733
Best Val Acc: 0.9733
Test Acc: 0.9765
Runtime (sec): 74.08
================================================================================
MNIST | MLP-shallow | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8731 | Val Acc: 0.9262
Epoch 02 | Train Acc: 0.9341 | Val Acc: 0.9443
Epoch 03 | Train Acc: 0.9504 | Val Acc: 0.9528
Epoch 04 | Train Acc: 0.9585 | Val Acc: 0.9587
Epoch 05 | Train Acc: 0.9648 | Val Acc: 0.9628
Epoch 06 | Train Acc: 0.9697 | Val Acc: 0.9651
Epoch 07 | Train Acc: 0.9728 | Val Acc: 0.9679
Epoch 08 | Train Acc: 0.9747 | Val Acc: 0.9698
Best Val Acc: 0.9698
Test Acc: 0.9746
Runtime (sec): 56.47
================================================================================
MNIST | MLP-shallow | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.8604 | Val Acc: 0.9297
Epoch 02 | Train Acc: 0.9225 | Val Acc: 0.9473
Epoch 03 | Train Acc: 0.9380 | Val Acc: 0.9572
Epoch 04 | Train Acc: 0.9461 | Val Acc: 0.9606
Epoch 05 | Train Acc: 0.9508 | Val Acc: 0.9622
Epoch 06 | Train Acc: 0.9542 | Val Acc: 0.9626
Epoch 07 | Train Acc: 0.9562 | Val Acc: 0.9678
Epoch 08 | Train Acc: 0.9583 | Val Acc: 0.9689
Best Val Acc: 0.9689
Test Acc: 0.9711
Runtime (sec): 63.26
================================================================================
MNIST | MLP-shallow | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.5233 | Val Acc: 0.7781
Epoch 02 | Train Acc: 0.7309 | Val Acc: 0.8449
Epoch 03 | Train Acc: 0.7891 | Val Acc: 0.8672
Epoch 04 | Train Acc: 0.8186 | Val Acc: 0.8780
Epoch 05 | Train Acc: 0.8372 | Val Acc: 0.8855
Epoch 06 | Train Acc: 0.8506 | Val Acc: 0.8903
Epoch 07 | Train Acc: 0.8583 | Val Acc: 0.8935
Epoch 08 | Train Acc: 0.8665 | Val Acc: 0.8982
Best Val Acc: 0.8982
Test Acc: 0.9064
Runtime (sec): 55.42
================================================================================
MNIST | MLP-shallow | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.7594 | Val Acc: 0.8870
Epoch 02 | Train Acc: 0.8690 | Val Acc: 0.9056
Epoch 03 | Train Acc: 0.8919 | Val Acc: 0.9155
Epoch 04 | Train Acc: 0.9039 | Val Acc: 0.9214
Epoch 05 | Train Acc: 0.9113 | Val Acc: 0.9294
Epoch 06 | Train Acc: 0.9197 | Val Acc: 0.9342
Epoch 07 | Train Acc: 0.9229 | Val Acc: 0.9376
Epoch 08 | Train Acc: 0.9283 | Val Acc: 0.9405
Best Val Acc: 0.9405
Test Acc: 0.946
Runtime (sec): 74.4

In [ ]:
mnist_shallow_df

,dataset,architecture,hidden_layers,lr,batch_size,optimizer,dropout,best_val_acc,test_acc,runtime_sec
0,MNIST,shallow,[128],0.0010,32,Adam,0.2,0.9733,0.9765,74.081670
1,MNIST,shallow,[128],0.0010,64,Adam,0.2,0.9718,0.9765,62.991311
2,MNIST,shallow,[128],0.0010,128,Adam,0.2,0.9698,0.9746,56.465903
3,MNIST,shallow,[128],0.0010,64,Adam,0.5,0.9689,0.9711,63.261419
4,MNIST,shallow,[128],0.0100,64,Adam,0.2,0.9641,0.9662,62.469495
5,MNIST,shallow,[128],0.0001,32,Adam,0.5,0.9405,0.9460,74.396330
6,MNIST,shallow,[128],0.0001,64,Adam,0.2,0.9358,0.9404,62.460160
7,MNIST,shallow,[128],0.0100,64,SGD,0.2,0.9158,0.9239,60.872779
8,MNIST,shallow,[128],0.0100,128,SGD,0.5,0.8982,0.9064,55.417305
9,MNIST,shallow,[128],0.0010,64,SGD,0.2,0.8250,0.8310,61.150095

In [ ]:
mnist_shallow_best

{'dataset': 'MNIST',
 'architecture': 'shallow',
 'hidden_layers': '[128]',
 'lr': 0.001,
 'batch_size': 32,
 'optimizer': 'Adam',
 'dropout': 0.2,
 'best_val_acc': 0.9733,
 'test_acc': 0.9765,
 'runtime_sec': 74.08166980743408}

In [ ]:
mnist_shallow_df.to_csv("mnist_mlp_shallow_tuning.csv", index=False)
print("Saved mnist_mlp_shallow_tuning.csv")

Saved mnist_mlp_shallow_tuning.csv

In [ ]:
mnist_medium_df, mnist_medium_best = tune_mlp_architecture(
    dataset_name="MNIST",
    architecture_name="medium",
    hidden_layers=MLP_ARCHITECTURES["medium"],
    train_dataset=mnist_train,
    val_dataset=mnist_val,
    test_dataset=mnist_test,
    configs=mlp_configs,
    epochs=8,
    patience=2
)

================================================================================
MNIST | MLP-medium | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.3354 | Val Acc: 0.5954
Epoch 02 | Train Acc: 0.6186 | Val Acc: 0.7960
Epoch 03 | Train Acc: 0.7836 | Val Acc: 0.8584
Epoch 04 | Train Acc: 0.8443 | Val Acc: 0.8846
Epoch 05 | Train Acc: 0.8690 | Val Acc: 0.8991
Epoch 06 | Train Acc: 0.8862 | Val Acc: 0.9084
Epoch 07 | Train Acc: 0.8987 | Val Acc: 0.9157
Epoch 08 | Train Acc: 0.9086 | Val Acc: 0.9219
Best Val Acc: 0.9219
Test Acc: 0.9266
Runtime (sec): 65.6
================================================================================
MNIST | MLP-medium | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8767 | Val Acc: 0.9347
Epoch 02 | Train Acc: 0.9114 | Val Acc: 0.9331
Epoch 03 | Train Acc: 0.9177 | Val Acc: 0.9362
Epoch 04 | Train Acc: 0.9194 | Val Acc: 0.9432
Epoch 05 | Train Acc: 0.9192 | Val Acc: 0.9475
Epoch 06 | Train Acc: 0.9257 | Val Acc: 0.9524
Epoch 07 | Train Acc: 0.9287 | Val Acc: 0.9466
Epoch 08 | Train Acc: 0.9305 | Val Acc: 0.9457
Early stopping triggered.
Best Val Acc: 0.9524
Test Acc: 0.9455
Runtime (sec): 67.19
================================================================================
MNIST | MLP-medium | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.0994 | Val Acc: 0.0985
Epoch 02 | Train Acc: 0.1052 | Val Acc: 0.0984
Epoch 03 | Train Acc: 0.1300 | Val Acc: 0.1541
Epoch 04 | Train Acc: 0.1898 | Val Acc: 0.2159
Epoch 05 | Train Acc: 0.2535 | Val Acc: 0.3340
Epoch 06 | Train Acc: 0.3297 | Val Acc: 0.4673
Epoch 07 | Train Acc: 0.4088 | Val Acc: 0.5639
Epoch 08 | Train Acc: 0.4711 | Val Acc: 0.6206
Best Val Acc: 0.6206
Test Acc: 0.6264
Runtime (sec): 64.35
================================================================================
MNIST | MLP-medium | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.9034 | Val Acc: 0.9523
Epoch 02 | Train Acc: 0.9614 | Val Acc: 0.9686
Epoch 03 | Train Acc: 0.9724 | Val Acc: 0.9712
Epoch 04 | Train Acc: 0.9758 | Val Acc: 0.9752
Epoch 05 | Train Acc: 0.9806 | Val Acc: 0.9758
Epoch 06 | Train Acc: 0.9826 | Val Acc: 0.9750
Epoch 07 | Train Acc: 0.9844 | Val Acc: 0.9773
Epoch 08 | Train Acc: 0.9867 | Val Acc: 0.9790
Best Val Acc: 0.979
Test Acc: 0.9784
Runtime (sec): 66.04
================================================================================
MNIST | MLP-medium | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.7797 | Val Acc: 0.9050
Epoch 02 | Train Acc: 0.9079 | Val Acc: 0.9300
Epoch 03 | Train Acc: 0.9327 | Val Acc: 0.9436
Epoch 04 | Train Acc: 0.9451 | Val Acc: 0.9515
Epoch 05 | Train Acc: 0.9536 | Val Acc: 0.9573
Epoch 06 | Train Acc: 0.9597 | Val Acc: 0.9598
Epoch 07 | Train Acc: 0.9658 | Val Acc: 0.9641
Epoch 08 | Train Acc: 0.9699 | Val Acc: 0.9656
Best Val Acc: 0.9656
Test Acc: 0.9715
Runtime (sec): 66.71
================================================================================
MNIST | MLP-medium | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.9099 | Val Acc: 0.9590
Epoch 02 | Train Acc: 0.9605 | Val Acc: 0.9676
Epoch 03 | Train Acc: 0.9704 | Val Acc: 0.9674
Epoch 04 | Train Acc: 0.9757 | Val Acc: 0.9671
Early stopping triggered.
Best Val Acc: 0.9676
Test Acc: 0.9712
Runtime (sec): 41.52
================================================================================
MNIST | MLP-medium | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8817 | Val Acc: 0.9505
Epoch 02 | Train Acc: 0.9583 | Val Acc: 0.9616
Epoch 03 | Train Acc: 0.9694 | Val Acc: 0.9674
Epoch 04 | Train Acc: 0.9755 | Val Acc: 0.9726
Epoch 05 | Train Acc: 0.9803 | Val Acc: 0.9753
Epoch 06 | Train Acc: 0.9834 | Val Acc: 0.9765
Epoch 07 | Train Acc: 0.9847 | Val Acc: 0.9740
Epoch 08 | Train Acc: 0.9871 | Val Acc: 0.9745
Early stopping triggered.
Best Val Acc: 0.9765
Test Acc: 0.977
Runtime (sec): 57.88
================================================================================
MNIST | MLP-medium | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.8596 | Val Acc: 0.9492
Epoch 02 | Train Acc: 0.9431 | Val Acc: 0.9628
Epoch 03 | Train Acc: 0.9530 | Val Acc: 0.9662
Epoch 04 | Train Acc: 0.9589 | Val Acc: 0.9692
Epoch 05 | Train Acc: 0.9631 | Val Acc: 0.9723
Epoch 06 | Train Acc: 0.9661 | Val Acc: 0.9730
Epoch 07 | Train Acc: 0.9694 | Val Acc: 0.9729
Epoch 08 | Train Acc: 0.9710 | Val Acc: 0.9757
Best Val Acc: 0.9757
Test Acc: 0.9784
Runtime (sec): 66.69
================================================================================
MNIST | MLP-medium | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1248 | Val Acc: 0.2548
Epoch 02 | Train Acc: 0.2206 | Val Acc: 0.5239
Epoch 03 | Train Acc: 0.3460 | Val Acc: 0.6231
Epoch 04 | Train Acc: 0.4860 | Val Acc: 0.7304
Epoch 05 | Train Acc: 0.6076 | Val Acc: 0.7816
Epoch 06 | Train Acc: 0.6925 | Val Acc: 0.8247
Epoch 07 | Train Acc: 0.7461 | Val Acc: 0.8491
Epoch 08 | Train Acc: 0.7813 | Val Acc: 0.8640
Best Val Acc: 0.864
Test Acc: 0.8728
Runtime (sec): 57.15
================================================================================
MNIST | MLP-medium | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.7095 | Val Acc: 0.9029
Epoch 02 | Train Acc: 0.8896 | Val Acc: 0.9261
Epoch 03 | Train Acc: 0.9180 | Val Acc: 0.9429
Epoch 04 | Train Acc: 0.9364 | Val Acc: 0.9514
Epoch 05 | Train Acc: 0.9467 | Val Acc: 0.9572
Epoch 06 | Train Acc: 0.9520 | Val Acc: 0.9614
Epoch 07 | Train Acc: 0.9585 | Val Acc: 0.9648
Epoch 08 | Train Acc: 0.9611 | Val Acc: 0.9653
Best Val Acc: 0.9653
Test Acc: 0.9712
Runtime (sec): 82.8

In [ ]:
mnist_deep_df, mnist_deep_best = tune_mlp_architecture(
    dataset_name="MNIST",
    architecture_name="deep",
    hidden_layers=MLP_ARCHITECTURES["deep"],
    train_dataset=mnist_train,
    val_dataset=mnist_val,
    test_dataset=mnist_test,
    configs=mlp_configs,
    epochs=8,
    patience=2
)

================================================================================
MNIST | MLP-deep | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1066 | Val Acc: 0.1829
Epoch 02 | Train Acc: 0.1265 | Val Acc: 0.1129
Epoch 03 | Train Acc: 0.1289 | Val Acc: 0.2094
Epoch 04 | Train Acc: 0.2691 | Val Acc: 0.3110
Epoch 05 | Train Acc: 0.4223 | Val Acc: 0.6306
Epoch 06 | Train Acc: 0.6461 | Val Acc: 0.7896
Epoch 07 | Train Acc: 0.7705 | Val Acc: 0.8407
Epoch 08 | Train Acc: 0.8378 | Val Acc: 0.8935
Best Val Acc: 0.8935
Test Acc: 0.894
Runtime (sec): 68.87
================================================================================
MNIST | MLP-deep | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.7980 | Val Acc: 0.8686
Epoch 02 | Train Acc: 0.8406 | Val Acc: 0.9122
Epoch 03 | Train Acc: 0.8494 | Val Acc: 0.9264
Epoch 04 | Train Acc: 0.7315 | Val Acc: 0.7135
Epoch 05 | Train Acc: 0.3647 | Val Acc: 0.3263
Early stopping triggered.
Best Val Acc: 0.9264
Test Acc: 0.3182
Runtime (sec): 44.55
================================================================================
MNIST | MLP-deep | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.0981 | Val Acc: 0.0985
Epoch 02 | Train Acc: 0.0973 | Val Acc: 0.0985
Epoch 03 | Train Acc: 0.1011 | Val Acc: 0.0985
Early stopping triggered.
Best Val Acc: 0.0985
Test Acc: 0.0958
Runtime (sec): 25.59
================================================================================
MNIST | MLP-deep | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8761 | Val Acc: 0.9564
Epoch 02 | Train Acc: 0.9592 | Val Acc: 0.9656
Epoch 03 | Train Acc: 0.9691 | Val Acc: 0.9707
Epoch 04 | Train Acc: 0.9738 | Val Acc: 0.9711
Epoch 05 | Train Acc: 0.9792 | Val Acc: 0.9727
Epoch 06 | Train Acc: 0.9818 | Val Acc: 0.9772
Epoch 07 | Train Acc: 0.9827 | Val Acc: 0.9763
Epoch 08 | Train Acc: 0.9843 | Val Acc: 0.9766
Early stopping triggered.
Best Val Acc: 0.9772
Test Acc: 0.9806
Runtime (sec): 70.82
================================================================================
MNIST | MLP-deep | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.7063 | Val Acc: 0.8983
Epoch 02 | Train Acc: 0.9019 | Val Acc: 0.9326
Epoch 03 | Train Acc: 0.9342 | Val Acc: 0.9485
Epoch 04 | Train Acc: 0.9496 | Val Acc: 0.9572
Epoch 05 | Train Acc: 0.9602 | Val Acc: 0.9608
Epoch 06 | Train Acc: 0.9665 | Val Acc: 0.9636
Epoch 07 | Train Acc: 0.9717 | Val Acc: 0.9665
Epoch 08 | Train Acc: 0.9758 | Val Acc: 0.9712
Best Val Acc: 0.9712
Test Acc: 0.9743
Runtime (sec): 70.06
================================================================================
MNIST | MLP-deep | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8944 | Val Acc: 0.9475
Epoch 02 | Train Acc: 0.9576 | Val Acc: 0.9538
Epoch 03 | Train Acc: 0.9675 | Val Acc: 0.9677
Epoch 04 | Train Acc: 0.9744 | Val Acc: 0.9758
Epoch 05 | Train Acc: 0.9761 | Val Acc: 0.9717
Epoch 06 | Train Acc: 0.9808 | Val Acc: 0.9772
Epoch 07 | Train Acc: 0.9806 | Val Acc: 0.9731
Epoch 08 | Train Acc: 0.9845 | Val Acc: 0.9753
Early stopping triggered.
Best Val Acc: 0.9772
Test Acc: 0.977
Runtime (sec): 91.79
================================================================================
MNIST | MLP-deep | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.8456 | Val Acc: 0.9460
Epoch 02 | Train Acc: 0.9558 | Val Acc: 0.9633
Epoch 03 | Train Acc: 0.9686 | Val Acc: 0.9693
Epoch 04 | Train Acc: 0.9751 | Val Acc: 0.9727
Epoch 05 | Train Acc: 0.9786 | Val Acc: 0.9696
Epoch 06 | Train Acc: 0.9822 | Val Acc: 0.9709
Early stopping triggered.
Best Val Acc: 0.9727
Test Acc: 0.9742
Runtime (sec): 45.51
================================================================================
MNIST | MLP-deep | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.7747 | Val Acc: 0.9381
Epoch 02 | Train Acc: 0.9327 | Val Acc: 0.9561
Epoch 03 | Train Acc: 0.9477 | Val Acc: 0.9641
Epoch 04 | Train Acc: 0.9542 | Val Acc: 0.9658
Epoch 05 | Train Acc: 0.9600 | Val Acc: 0.9680
Epoch 06 | Train Acc: 0.9613 | Val Acc: 0.9703
Epoch 07 | Train Acc: 0.9647 | Val Acc: 0.9703
Epoch 08 | Train Acc: 0.9667 | Val Acc: 0.9734
Best Val Acc: 0.9734
Test Acc: 0.9766
Runtime (sec): 71.78
================================================================================
MNIST | MLP-deep | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.0998 | Val Acc: 0.0964
Epoch 02 | Train Acc: 0.1097 | Val Acc: 0.1129
Epoch 03 | Train Acc: 0.1172 | Val Acc: 0.1129
Epoch 04 | Train Acc: 0.1198 | Val Acc: 0.1129
Early stopping triggered.
Best Val Acc: 0.1129
Test Acc: 0.1135
Runtime (sec): 29.79
================================================================================
MNIST | MLP-deep | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.5331 | Val Acc: 0.8606
Epoch 02 | Train Acc: 0.8373 | Val Acc: 0.9315
Epoch 03 | Train Acc: 0.9128 | Val Acc: 0.9483
Epoch 04 | Train Acc: 0.9375 | Val Acc: 0.9571
Epoch 05 | Train Acc: 0.9470 | Val Acc: 0.9621
Epoch 06 | Train Acc: 0.9563 | Val Acc: 0.9649
Epoch 07 | Train Acc: 0.9627 | Val Acc: 0.9667
Epoch 08 | Train Acc: 0.9662 | Val Acc: 0.9688
Best Val Acc: 0.9688
Test Acc: 0.9718
Runtime (sec): 90.66

In [ ]:
mnist_mlp_best_df = pd.DataFrame([
    mnist_shallow_best,
    mnist_medium_best,
    mnist_deep_best
])

mnist_mlp_best_df

,dataset,architecture,hidden_layers,lr,batch_size,optimizer,dropout,best_val_acc,test_acc,runtime_sec
0,MNIST,shallow,[128],0.001,32,Adam,0.2,0.9733,0.9765,74.081670
1,MNIST,medium,"[512, 256, 128]",0.001,64,Adam,0.2,0.9790,0.9784,66.042226
2,MNIST,deep,"[1024, 512, 256, 128, 64]",0.001,64,Adam,0.2,0.9772,0.9806,70.815244

In [ ]:
mnist_mlp_best_df.to_csv("mnist_mlp_best_results.csv", index=False)

In [ ]:
cifar_shallow_df, cifar_shallow_best = tune_mlp_architecture(
    dataset_name="CIFAR10",
    architecture_name="shallow",
    hidden_layers=MLP_ARCHITECTURES["shallow"],
    train_dataset=cifar_train,
    val_dataset=cifar_val,
    test_dataset=cifar_test,
    configs=mlp_configs,
    epochs=10,
    patience=2
)

================================================================================
CIFAR10 | MLP-shallow | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2615 | Val Acc: 0.3104
Epoch 02 | Train Acc: 0.3320 | Val Acc: 0.3142
Epoch 03 | Train Acc: 0.3577 | Val Acc: 0.3404
Epoch 04 | Train Acc: 0.3749 | Val Acc: 0.3588
Epoch 05 | Train Acc: 0.3871 | Val Acc: 0.3846
Epoch 06 | Train Acc: 0.3997 | Val Acc: 0.3808
Epoch 07 | Train Acc: 0.4086 | Val Acc: 0.3620
Early stopping triggered.
Best Val Acc: 0.3846
Test Acc: 0.3585
Runtime (sec): 54.01
================================================================================
CIFAR10 | MLP-shallow | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.0993 | Val Acc: 0.0990
Epoch 02 | Train Acc: 0.0992 | Val Acc: 0.0994
Epoch 03 | Train Acc: 0.0995 | Val Acc: 0.0996
Epoch 04 | Train Acc: 0.0983 | Val Acc: 0.0986
Epoch 05 | Train Acc: 0.0984 | Val Acc: 0.0986
Early stopping triggered.
Best Val Acc: 0.0996
Test Acc: 0.1
Runtime (sec): 38.61
================================================================================
CIFAR10 | MLP-shallow | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1517 | Val Acc: 0.2094
Epoch 02 | Train Acc: 0.2234 | Val Acc: 0.2658
Epoch 03 | Train Acc: 0.2499 | Val Acc: 0.2766
Epoch 04 | Train Acc: 0.2629 | Val Acc: 0.2996
Epoch 05 | Train Acc: 0.2830 | Val Acc: 0.3088
Epoch 06 | Train Acc: 0.2902 | Val Acc: 0.3190
Epoch 07 | Train Acc: 0.3010 | Val Acc: 0.3230
Epoch 08 | Train Acc: 0.3082 | Val Acc: 0.3288
Epoch 09 | Train Acc: 0.3159 | Val Acc: 0.3348
Epoch 10 | Train Acc: 0.3209 | Val Acc: 0.3338
Best Val Acc: 0.3348
Test Acc: 0.336
Runtime (sec): 75.07
================================================================================
CIFAR10 | MLP-shallow | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2804 | Val Acc: 0.3462
Epoch 02 | Train Acc: 0.3298 | Val Acc: 0.3444
Epoch 03 | Train Acc: 0.3435 | Val Acc: 0.3830
Epoch 04 | Train Acc: 0.3560 | Val Acc: 0.3784
Epoch 05 | Train Acc: 0.3637 | Val Acc: 0.4006
Epoch 06 | Train Acc: 0.3698 | Val Acc: 0.3978
Epoch 07 | Train Acc: 0.3717 | Val Acc: 0.4124
Epoch 08 | Train Acc: 0.3815 | Val Acc: 0.3970
Epoch 09 | Train Acc: 0.3824 | Val Acc: 0.4062
Early stopping triggered.
Best Val Acc: 0.4124
Test Acc: 0.4137
Runtime (sec): 69.12
================================================================================
CIFAR10 | MLP-shallow | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2781 | Val Acc: 0.3338
Epoch 02 | Train Acc: 0.3399 | Val Acc: 0.3704
Epoch 03 | Train Acc: 0.3606 | Val Acc: 0.3824
Epoch 04 | Train Acc: 0.3772 | Val Acc: 0.3942
Epoch 05 | Train Acc: 0.3904 | Val Acc: 0.4040
Epoch 06 | Train Acc: 0.3975 | Val Acc: 0.4022
Epoch 07 | Train Acc: 0.4063 | Val Acc: 0.4144
Epoch 08 | Train Acc: 0.4114 | Val Acc: 0.4200
Epoch 09 | Train Acc: 0.4175 | Val Acc: 0.4308
Epoch 10 | Train Acc: 0.4214 | Val Acc: 0.4296
Best Val Acc: 0.4308
Test Acc: 0.4349
Runtime (sec): 77.23
================================================================================
CIFAR10 | MLP-shallow | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2776 | Val Acc: 0.3492
Epoch 02 | Train Acc: 0.3206 | Val Acc: 0.3648
Epoch 03 | Train Acc: 0.3341 | Val Acc: 0.3632
Epoch 04 | Train Acc: 0.3391 | Val Acc: 0.3864
Epoch 05 | Train Acc: 0.3436 | Val Acc: 0.3878
Epoch 06 | Train Acc: 0.3485 | Val Acc: 0.3924
Epoch 07 | Train Acc: 0.3546 | Val Acc: 0.3948
Epoch 08 | Train Acc: 0.3592 | Val Acc: 0.3904
Epoch 09 | Train Acc: 0.3636 | Val Acc: 0.4012
Epoch 10 | Train Acc: 0.3713 | Val Acc: 0.4150
Best Val Acc: 0.415
Test Acc: 0.4208
Runtime (sec): 89.77
================================================================================
CIFAR10 | MLP-shallow | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2935 | Val Acc: 0.3520
Epoch 02 | Train Acc: 0.3475 | Val Acc: 0.3754
Epoch 03 | Train Acc: 0.3604 | Val Acc: 0.3906
Epoch 04 | Train Acc: 0.3743 | Val Acc: 0.4172
Epoch 05 | Train Acc: 0.3837 | Val Acc: 0.4052
Epoch 06 | Train Acc: 0.3881 | Val Acc: 0.4262
Epoch 07 | Train Acc: 0.3929 | Val Acc: 0.4108
Epoch 08 | Train Acc: 0.3992 | Val Acc: 0.4360
Epoch 09 | Train Acc: 0.4001 | Val Acc: 0.4254
Epoch 10 | Train Acc: 0.4028 | Val Acc: 0.4310
Early stopping triggered.
Best Val Acc: 0.436
Test Acc: 0.4363
Runtime (sec): 70.78
================================================================================
CIFAR10 | MLP-shallow | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.2227 | Val Acc: 0.2890
Epoch 02 | Train Acc: 0.2482 | Val Acc: 0.3288
Epoch 03 | Train Acc: 0.2667 | Val Acc: 0.3276
Epoch 04 | Train Acc: 0.2688 | Val Acc: 0.3368
Epoch 05 | Train Acc: 0.2743 | Val Acc: 0.3492
Epoch 06 | Train Acc: 0.2765 | Val Acc: 0.3588
Epoch 07 | Train Acc: 0.2847 | Val Acc: 0.3582
Epoch 08 | Train Acc: 0.2797 | Val Acc: 0.3652
Epoch 09 | Train Acc: 0.2904 | Val Acc: 0.3662
Epoch 10 | Train Acc: 0.2937 | Val Acc: 0.3720
Best Val Acc: 0.372
Test Acc: 0.378
Runtime (sec): 76.18
================================================================================
CIFAR10 | MLP-shallow | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.2016 | Val Acc: 0.2936
Epoch 02 | Train Acc: 0.2729 | Val Acc: 0.3254
Epoch 03 | Train Acc: 0.3032 | Val Acc: 0.3368
Epoch 04 | Train Acc: 0.3226 | Val Acc: 0.3540
Epoch 05 | Train Acc: 0.3348 | Val Acc: 0.3624
Epoch 06 | Train Acc: 0.3424 | Val Acc: 0.3760
Epoch 07 | Train Acc: 0.3534 | Val Acc: 0.3794
Epoch 08 | Train Acc: 0.3615 | Val Acc: 0.3846
Epoch 09 | Train Acc: 0.3650 | Val Acc: 0.3846
Epoch 10 | Train Acc: 0.3744 | Val Acc: 0.3924
Best Val Acc: 0.3924
Test Acc: 0.3975
Runtime (sec): 69.91
================================================================================
CIFAR10 | MLP-shallow | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.2471 | Val Acc: 0.3374
Epoch 02 | Train Acc: 0.3038 | Val Acc: 0.3540
Epoch 03 | Train Acc: 0.3250 | Val Acc: 0.3694
Epoch 04 | Train Acc: 0.3354 | Val Acc: 0.3726
Epoch 05 | Train Acc: 0.3443 | Val Acc: 0.3806
Epoch 06 | Train Acc: 0.3527 | Val Acc: 0.3860
Epoch 07 | Train Acc: 0.3607 | Val Acc: 0.3962
Epoch 08 | Train Acc: 0.3655 | Val Acc: 0.4070
Epoch 09 | Train Acc: 0.3686 | Val Acc: 0.4042
Epoch 10 | Train Acc: 0.3723 | Val Acc: 0.4172
Best Val Acc: 0.4172
Test Acc: 0.4238
Runtime (sec): 89.25

In [ ]:
cifar_medium_df, cifar_medium_best = tune_mlp_architecture(
    dataset_name="CIFAR10",
    architecture_name="medium",
    hidden_layers=MLP_ARCHITECTURES["medium"],
    train_dataset=cifar_train,
    val_dataset=cifar_val,
    test_dataset=cifar_test,
    configs=mlp_configs,
    epochs=10,
    patience=2
)

================================================================================
CIFAR10 | MLP-medium | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1444 | Val Acc: 0.2142
Epoch 02 | Train Acc: 0.2214 | Val Acc: 0.2522
Epoch 03 | Train Acc: 0.2742 | Val Acc: 0.2938
Epoch 04 | Train Acc: 0.3080 | Val Acc: 0.3074
Epoch 05 | Train Acc: 0.3291 | Val Acc: 0.3446
Epoch 06 | Train Acc: 0.3462 | Val Acc: 0.3588
Epoch 07 | Train Acc: 0.3634 | Val Acc: 0.3818
Epoch 08 | Train Acc: 0.3727 | Val Acc: 0.3682
Epoch 09 | Train Acc: 0.3819 | Val Acc: 0.3910
Epoch 10 | Train Acc: 0.3923 | Val Acc: 0.3132
Best Val Acc: 0.391
Test Acc: 0.3111
Runtime (sec): 79.24
================================================================================
CIFAR10 | MLP-medium | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1767 | Val Acc: 0.2204
Epoch 02 | Train Acc: 0.1818 | Val Acc: 0.1764
Epoch 03 | Train Acc: 0.1667 | Val Acc: 0.1778
Early stopping triggered.
Best Val Acc: 0.2204
Test Acc: 0.1835
Runtime (sec): 24.42
================================================================================
CIFAR10 | MLP-medium | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1081 | Val Acc: 0.1586
Epoch 02 | Train Acc: 0.1256 | Val Acc: 0.1414
Epoch 03 | Train Acc: 0.1313 | Val Acc: 0.1456
Early stopping triggered.
Best Val Acc: 0.1586
Test Acc: 0.1474
Runtime (sec): 23.69
================================================================================
CIFAR10 | MLP-medium | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2803 | Val Acc: 0.3414
Epoch 02 | Train Acc: 0.3391 | Val Acc: 0.3720
Epoch 03 | Train Acc: 0.3586 | Val Acc: 0.3730
Epoch 04 | Train Acc: 0.3798 | Val Acc: 0.4108
Epoch 05 | Train Acc: 0.3896 | Val Acc: 0.4142
Epoch 06 | Train Acc: 0.4003 | Val Acc: 0.4236
Epoch 07 | Train Acc: 0.4029 | Val Acc: 0.4292
Epoch 08 | Train Acc: 0.4123 | Val Acc: 0.4466
Epoch 09 | Train Acc: 0.4159 | Val Acc: 0.4344
Epoch 10 | Train Acc: 0.4261 | Val Acc: 0.4562
Best Val Acc: 0.4562
Test Acc: 0.465
Runtime (sec): 82.43
================================================================================
CIFAR10 | MLP-medium | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2453 | Val Acc: 0.3324
Epoch 02 | Train Acc: 0.3371 | Val Acc: 0.3712
Epoch 03 | Train Acc: 0.3688 | Val Acc: 0.3978
Epoch 04 | Train Acc: 0.3902 | Val Acc: 0.4008
Epoch 05 | Train Acc: 0.4049 | Val Acc: 0.4146
Epoch 06 | Train Acc: 0.4205 | Val Acc: 0.4332
Epoch 07 | Train Acc: 0.4335 | Val Acc: 0.4462
Epoch 08 | Train Acc: 0.4447 | Val Acc: 0.4530
Epoch 09 | Train Acc: 0.4500 | Val Acc: 0.4648
Epoch 10 | Train Acc: 0.4572 | Val Acc: 0.4696
Best Val Acc: 0.4696
Test Acc: 0.4704
Runtime (sec): 82.21
================================================================================
CIFAR10 | MLP-medium | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2658 | Val Acc: 0.3288
Epoch 02 | Train Acc: 0.3217 | Val Acc: 0.3520
Epoch 03 | Train Acc: 0.3457 | Val Acc: 0.3644
Epoch 04 | Train Acc: 0.3621 | Val Acc: 0.3906
Epoch 05 | Train Acc: 0.3767 | Val Acc: 0.3984
Epoch 06 | Train Acc: 0.3789 | Val Acc: 0.4066
Epoch 07 | Train Acc: 0.3872 | Val Acc: 0.4126
Epoch 08 | Train Acc: 0.3936 | Val Acc: 0.4110
Epoch 09 | Train Acc: 0.3968 | Val Acc: 0.4372
Epoch 10 | Train Acc: 0.4001 | Val Acc: 0.4190
Best Val Acc: 0.4372
Test Acc: 0.4175
Runtime (sec): 98.24
================================================================================
CIFAR10 | MLP-medium | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.2769 | Val Acc: 0.3354
Epoch 02 | Train Acc: 0.3433 | Val Acc: 0.3718
Epoch 03 | Train Acc: 0.3691 | Val Acc: 0.4038
Epoch 04 | Train Acc: 0.3842 | Val Acc: 0.3842
Epoch 05 | Train Acc: 0.3960 | Val Acc: 0.4250
Epoch 06 | Train Acc: 0.4102 | Val Acc: 0.4352
Epoch 07 | Train Acc: 0.4156 | Val Acc: 0.4484
Epoch 08 | Train Acc: 0.4238 | Val Acc: 0.4434
Epoch 09 | Train Acc: 0.4277 | Val Acc: 0.4514
Epoch 10 | Train Acc: 0.4348 | Val Acc: 0.4624
Best Val Acc: 0.4624
Test Acc: 0.466
Runtime (sec): 72.52
================================================================================
CIFAR10 | MLP-medium | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1868 | Val Acc: 0.2366
Epoch 02 | Train Acc: 0.2282 | Val Acc: 0.2658
Epoch 03 | Train Acc: 0.2438 | Val Acc: 0.2902
Epoch 04 | Train Acc: 0.2509 | Val Acc: 0.2922
Epoch 05 | Train Acc: 0.2548 | Val Acc: 0.2932
Epoch 06 | Train Acc: 0.2574 | Val Acc: 0.2986
Epoch 07 | Train Acc: 0.2663 | Val Acc: 0.2954
Epoch 08 | Train Acc: 0.2669 | Val Acc: 0.2844
Early stopping triggered.
Best Val Acc: 0.2986
Test Acc: 0.2841
Runtime (sec): 65.3
================================================================================
CIFAR10 | MLP-medium | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1170 | Val Acc: 0.1328
Epoch 02 | Train Acc: 0.1497 | Val Acc: 0.2308
Epoch 03 | Train Acc: 0.1734 | Val Acc: 0.1940
Epoch 04 | Train Acc: 0.1861 | Val Acc: 0.2254
Early stopping triggered.
Best Val Acc: 0.2308
Test Acc: 0.2342
Runtime (sec): 28.31
================================================================================
CIFAR10 | MLP-medium | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1764 | Val Acc: 0.2678
Epoch 02 | Train Acc: 0.2635 | Val Acc: 0.3232
Epoch 03 | Train Acc: 0.2982 | Val Acc: 0.3462
Epoch 04 | Train Acc: 0.3194 | Val Acc: 0.3590
Epoch 05 | Train Acc: 0.3353 | Val Acc: 0.3698
Epoch 06 | Train Acc: 0.3468 | Val Acc: 0.3844
Epoch 07 | Train Acc: 0.3562 | Val Acc: 0.3924
Epoch 08 | Train Acc: 0.3660 | Val Acc: 0.3980
Epoch 09 | Train Acc: 0.3708 | Val Acc: 0.4102
Epoch 10 | Train Acc: 0.3766 | Val Acc: 0.4042
Best Val Acc: 0.4102
Test Acc: 0.4069
Runtime (sec): 97.96

In [ ]:
cifar_deep_df, cifar_deep_best = tune_mlp_architecture(
    dataset_name="CIFAR10",
    architecture_name="deep",
    hidden_layers=MLP_ARCHITECTURES["deep"],
    train_dataset=cifar_train,
    val_dataset=cifar_val,
    test_dataset=cifar_test,
    configs=mlp_configs,
    epochs=10,
    patience=2
)

================================================================================
CIFAR10 | MLP-deep | Config 1/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1019 | Val Acc: 0.0968
Epoch 02 | Train Acc: 0.1176 | Val Acc: 0.1636
Epoch 03 | Train Acc: 0.1455 | Val Acc: 0.1560
Epoch 04 | Train Acc: 0.1719 | Val Acc: 0.1810
Epoch 05 | Train Acc: 0.1845 | Val Acc: 0.1600
Epoch 06 | Train Acc: 0.1902 | Val Acc: 0.1932
Epoch 07 | Train Acc: 0.1986 | Val Acc: 0.2032
Epoch 08 | Train Acc: 0.2061 | Val Acc: 0.1324
Epoch 09 | Train Acc: 0.2156 | Val Acc: 0.2146
Epoch 10 | Train Acc: 0.2251 | Val Acc: 0.1862
Best Val Acc: 0.2146
Test Acc: 0.193
Runtime (sec): 83.54
================================================================================
CIFAR10 | MLP-deep | Config 2/10
{'lr': 0.01, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1417 | Val Acc: 0.1696
Epoch 02 | Train Acc: 0.1475 | Val Acc: 0.1750
Epoch 03 | Train Acc: 0.1544 | Val Acc: 0.1836
Epoch 04 | Train Acc: 0.1532 | Val Acc: 0.1556
Epoch 05 | Train Acc: 0.1394 | Val Acc: 0.1092
Early stopping triggered.
Best Val Acc: 0.1836
Test Acc: 0.1097
Runtime (sec): 42.96
================================================================================
CIFAR10 | MLP-deep | Config 3/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'SGD', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1006 | Val Acc: 0.0966
Epoch 02 | Train Acc: 0.1025 | Val Acc: 0.0972
Epoch 03 | Train Acc: 0.1022 | Val Acc: 0.0970
Epoch 04 | Train Acc: 0.1050 | Val Acc: 0.0970
Early stopping triggered.
Best Val Acc: 0.0972
Test Acc: 0.1023
Runtime (sec): 33.15
================================================================================
CIFAR10 | MLP-deep | Config 4/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1755 | Val Acc: 0.2236
Epoch 02 | Train Acc: 0.2600 | Val Acc: 0.3098
Epoch 03 | Train Acc: 0.2986 | Val Acc: 0.3122
Epoch 04 | Train Acc: 0.3225 | Val Acc: 0.3298
Epoch 05 | Train Acc: 0.3382 | Val Acc: 0.3482
Epoch 06 | Train Acc: 0.3451 | Val Acc: 0.3708
Epoch 07 | Train Acc: 0.3574 | Val Acc: 0.3900
Epoch 08 | Train Acc: 0.3664 | Val Acc: 0.3868
Epoch 09 | Train Acc: 0.3769 | Val Acc: 0.4046
Epoch 10 | Train Acc: 0.3825 | Val Acc: 0.4182
Best Val Acc: 0.4182
Test Acc: 0.4186
Runtime (sec): 85.26
================================================================================
CIFAR10 | MLP-deep | Config 5/10
{'lr': 0.0001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1990 | Val Acc: 0.2972
Epoch 02 | Train Acc: 0.2945 | Val Acc: 0.3296
Epoch 03 | Train Acc: 0.3295 | Val Acc: 0.3594
Epoch 04 | Train Acc: 0.3550 | Val Acc: 0.3826
Epoch 05 | Train Acc: 0.3765 | Val Acc: 0.3818
Epoch 06 | Train Acc: 0.3961 | Val Acc: 0.4138
Epoch 07 | Train Acc: 0.4119 | Val Acc: 0.4242
Epoch 08 | Train Acc: 0.4235 | Val Acc: 0.4418
Epoch 09 | Train Acc: 0.4362 | Val Acc: 0.4504
Epoch 10 | Train Acc: 0.4439 | Val Acc: 0.4446
Best Val Acc: 0.4504
Test Acc: 0.452
Runtime (sec): 85.23
================================================================================
CIFAR10 | MLP-deep | Config 6/10
{'lr': 0.001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1902 | Val Acc: 0.2546
Epoch 02 | Train Acc: 0.2676 | Val Acc: 0.2936
Epoch 03 | Train Acc: 0.2862 | Val Acc: 0.3090
Epoch 04 | Train Acc: 0.2999 | Val Acc: 0.3250
Epoch 05 | Train Acc: 0.3113 | Val Acc: 0.3334
Epoch 06 | Train Acc: 0.3144 | Val Acc: 0.3502
Epoch 07 | Train Acc: 0.3200 | Val Acc: 0.3552
Epoch 08 | Train Acc: 0.3300 | Val Acc: 0.3506
Epoch 09 | Train Acc: 0.3364 | Val Acc: 0.3626
Epoch 10 | Train Acc: 0.3470 | Val Acc: 0.3690
Best Val Acc: 0.369
Test Acc: 0.3802
Runtime (sec): 106.89
================================================================================
CIFAR10 | MLP-deep | Config 7/10
{'lr': 0.001, 'batch_size': 128, 'optimizer': 'Adam', 'dropout': 0.2}
Epoch 01 | Train Acc: 0.1965 | Val Acc: 0.2598
Epoch 02 | Train Acc: 0.2782 | Val Acc: 0.3256
Epoch 03 | Train Acc: 0.3211 | Val Acc: 0.3498
Epoch 04 | Train Acc: 0.3381 | Val Acc: 0.3676
Epoch 05 | Train Acc: 0.3572 | Val Acc: 0.3842
Epoch 06 | Train Acc: 0.3676 | Val Acc: 0.3960
Epoch 07 | Train Acc: 0.3802 | Val Acc: 0.4072
Epoch 08 | Train Acc: 0.3879 | Val Acc: 0.4234
Epoch 09 | Train Acc: 0.3958 | Val Acc: 0.4196
Epoch 10 | Train Acc: 0.4039 | Val Acc: 0.4128
Early stopping triggered.
Best Val Acc: 0.4234
Test Acc: 0.4256
Runtime (sec): 73.81
================================================================================
CIFAR10 | MLP-deep | Config 8/10
{'lr': 0.001, 'batch_size': 64, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1444 | Val Acc: 0.1746
Epoch 02 | Train Acc: 0.1755 | Val Acc: 0.1768
Epoch 03 | Train Acc: 0.1780 | Val Acc: 0.2260
Epoch 04 | Train Acc: 0.1878 | Val Acc: 0.1922
Epoch 05 | Train Acc: 0.1992 | Val Acc: 0.2302
Epoch 06 | Train Acc: 0.2116 | Val Acc: 0.2204
Epoch 07 | Train Acc: 0.2110 | Val Acc: 0.2320
Epoch 08 | Train Acc: 0.2171 | Val Acc: 0.2362
Epoch 09 | Train Acc: 0.2208 | Val Acc: 0.2322
Epoch 10 | Train Acc: 0.2226 | Val Acc: 0.2588
Best Val Acc: 0.2588
Test Acc: 0.2582
Runtime (sec): 85.6
================================================================================
CIFAR10 | MLP-deep | Config 9/10
{'lr': 0.01, 'batch_size': 128, 'optimizer': 'SGD', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.0995 | Val Acc: 0.0958
Epoch 02 | Train Acc: 0.1002 | Val Acc: 0.0958
Epoch 03 | Train Acc: 0.1035 | Val Acc: 0.0958
Early stopping triggered.
Best Val Acc: 0.0958
Test Acc: 0.1
Runtime (sec): 21.7
================================================================================
CIFAR10 | MLP-deep | Config 10/10
{'lr': 0.0001, 'batch_size': 32, 'optimizer': 'Adam', 'dropout': 0.5}
Epoch 01 | Train Acc: 0.1297 | Val Acc: 0.1700
Epoch 02 | Train Acc: 0.1713 | Val Acc: 0.1810
Epoch 03 | Train Acc: 0.1805 | Val Acc: 0.1958
Epoch 04 | Train Acc: 0.2079 | Val Acc: 0.2502
Epoch 05 | Train Acc: 0.2339 | Val Acc: 0.2732
Epoch 06 | Train Acc: 0.2538 | Val Acc: 0.2934
Epoch 07 | Train Acc: 0.2700 | Val Acc: 0.3110
Epoch 08 | Train Acc: 0.2785 | Val Acc: 0.3290
Epoch 09 | Train Acc: 0.2900 | Val Acc: 0.3384
Epoch 10 | Train Acc: 0.2979 | Val Acc: 0.3424
Best Val Acc: 0.3424
Test Acc: 0.3504
Runtime (sec): 107.1

In [ ]:
cifar_mlp_best_df = pd.DataFrame([
    cifar_shallow_best,
    cifar_medium_best,
    cifar_deep_best
])

cifar_mlp_best_df

,dataset,architecture,hidden_layers,lr,batch_size,optimizer,dropout,best_val_acc,test_acc,runtime_sec
0,CIFAR10,shallow,[128],0.0010,128,Adam,0.2,0.4360,0.4363,70.780890
1,CIFAR10,medium,"[512, 256, 128]",0.0001,64,Adam,0.2,0.4696,0.4704,82.211029
2,CIFAR10,deep,"[1024, 512, 256, 128, 64]",0.0001,64,Adam,0.2,0.4504,0.4520,85.229198

In [ ]:
mnist_shallow_df.to_csv("mnist_mlp_shallow_tuning.csv", index=False)
mnist_medium_df.to_csv("mnist_mlp_medium_tuning.csv", index=False)
mnist_deep_df.to_csv("mnist_mlp_deep_tuning.csv", index=False)

cifar_shallow_df.to_csv("cifar_mlp_shallow_tuning.csv", index=False)
cifar_medium_df.to_csv("cifar_mlp_medium_tuning.csv", index=False)
cifar_deep_df.to_csv("cifar_mlp_deep_tuning.csv", index=False)

mnist_mlp_best_df.to_csv("mnist_mlp_best_results.csv", index=False)
cifar_mlp_best_df.to_csv("cifar_mlp_best_results.csv", index=False)

print("All MLP CSVs saved.")

All MLP CSVs saved.

In [37]:
cnn_configs = [
    {"lr": 0.01,   "batch_size": 32,  "weight_decay": 0.0},
    {"lr": 0.01,   "batch_size": 64,  "weight_decay": 1e-4},
    {"lr": 0.01,   "batch_size": 128, "weight_decay": 5e-3},

    {"lr": 0.001,  "batch_size": 32,  "weight_decay": 0.0},
    {"lr": 0.001,  "batch_size": 64,  "weight_decay": 1e-4},
    {"lr": 0.001,  "batch_size": 128, "weight_decay": 5e-3},

    {"lr": 0.0001, "batch_size": 32,  "weight_decay": 0.0},
    {"lr": 0.0001, "batch_size": 64,  "weight_decay": 1e-4},
    {"lr": 0.0001, "batch_size": 128, "weight_decay": 5e-3},
]

len(cnn_configs)

9

In [38]:
def run_cnn_experiment(dataset_name, architecture_name, config,
                       train_dataset, val_dataset, test_dataset,
                       epochs=10, patience=3):

    if dataset_name == "MNIST":
        in_channels = 1
    elif dataset_name == "CIFAR10":
        in_channels = 3
    else:
        raise ValueError("dataset_name must be 'MNIST' or 'CIFAR10'")

    batch_size = config["batch_size"]
    train_loader, val_loader, test_loader = make_loaders(
        train_dataset, val_dataset, test_dataset, batch_size
    )

    if architecture_name == "simple":
        model = SimpleCNN(in_channels=in_channels).to(device)
    elif architecture_name == "enhanced":
        model = EnhancedCNN(in_channels=in_channels).to(device)
    else:
        raise ValueError("architecture_name must be 'simple' or 'enhanced'")

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(
        model.parameters(),
        lr=config["lr"],
        weight_decay=config["weight_decay"]
    )

    model, best_val_acc, runtime, history = train_model(
        model, train_loader, val_loader, optimizer, criterion, device,
        epochs=epochs, patience=patience
    )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    result = {
        "dataset": dataset_name,
        "architecture": architecture_name,
        "lr": config["lr"],
        "batch_size": config["batch_size"],
        "weight_decay": config["weight_decay"],
        "best_val_acc": best_val_acc,
        "test_acc": test_acc,
        "runtime_sec": runtime
    }

    return result, history

In [39]:
def tune_cnn_architecture(dataset_name, architecture_name,
                          train_dataset, val_dataset, test_dataset,
                          configs, epochs=10, patience=3):

    all_results = []
    best_result = None
    best_val_acc = -1

    for i, config in enumerate(configs, start=1):
        print("=" * 80)
        print(f"{dataset_name} | CNN-{architecture_name} | Config {i}/{len(configs)}")
        print(config)

        result, history = run_cnn_experiment(
            dataset_name=dataset_name,
            architecture_name=architecture_name,
            config=config,
            train_dataset=train_dataset,
            val_dataset=val_dataset,
            test_dataset=test_dataset,
            epochs=epochs,
            patience=patience
        )

        all_results.append(result)

        print("Best Val Acc:", round(result["best_val_acc"], 4))
        print("Test Acc:", round(result["test_acc"], 4))
        print("Runtime (sec):", round(result["runtime_sec"], 2))

        if result["best_val_acc"] > best_val_acc:
            best_val_acc = result["best_val_acc"]
            best_result = result

    df = pd.DataFrame(all_results).sort_values(by="best_val_acc", ascending=False).reset_index(drop=True)
    return df, best_result

In [40]:
mnist_simple_cnn_df, mnist_simple_cnn_best = tune_cnn_architecture(
    dataset_name="MNIST",
    architecture_name="simple",
    train_dataset=mnist_train,
    val_dataset=mnist_val,
    test_dataset=mnist_test,
    configs=cnn_configs,
    epochs=8,
    patience=2
)

================================================================================
MNIST | CNN-simple | Config 1/9
{'lr': 0.01, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.9581 | Val Acc: 0.9768
Epoch 02 | Train Acc: 0.9789 | Val Acc: 0.9788
Epoch 03 | Train Acc: 0.9824 | Val Acc: 0.9809
Epoch 04 | Train Acc: 0.9845 | Val Acc: 0.9797
Epoch 05 | Train Acc: 0.9858 | Val Acc: 0.9834
Epoch 06 | Train Acc: 0.9863 | Val Acc: 0.9825
Epoch 07 | Train Acc: 0.9880 | Val Acc: 0.9825
Early stopping triggered.
Best Val Acc: 0.9834
Test Acc: 0.9855
Runtime (sec): 73.81
================================================================================
MNIST | CNN-simple | Config 2/9
{'lr': 0.01, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.9539 | Val Acc: 0.9749
Epoch 02 | Train Acc: 0.9780 | Val Acc: 0.9766
Epoch 03 | Train Acc: 0.9818 | Val Acc: 0.9812
Epoch 04 | Train Acc: 0.9830 | Val Acc: 0.9804
Epoch 05 | Train Acc: 0.9839 | Val Acc: 0.9832
Epoch 06 | Train Acc: 0.9856 | Val Acc: 0.9791
Epoch 07 | Train Acc: 0.9844 | Val Acc: 0.9792
Early stopping triggered.
Best Val Acc: 0.9832
Test Acc: 0.9802
Runtime (sec): 58.61
================================================================================
MNIST | CNN-simple | Config 3/9
{'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.9439 | Val Acc: 0.9501
Epoch 02 | Train Acc: 0.9720 | Val Acc: 0.9614
Epoch 03 | Train Acc: 0.9726 | Val Acc: 0.9681
Epoch 04 | Train Acc: 0.9739 | Val Acc: 0.9691
Epoch 05 | Train Acc: 0.9728 | Val Acc: 0.9383
Epoch 06 | Train Acc: 0.9740 | Val Acc: 0.9793
Epoch 07 | Train Acc: 0.9733 | Val Acc: 0.9444
Epoch 08 | Train Acc: 0.9742 | Val Acc: 0.9695
Early stopping triggered.
Best Val Acc: 0.9793
Test Acc: 0.9738
Runtime (sec): 57.51
================================================================================
MNIST | CNN-simple | Config 4/9
{'lr': 0.001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.9361 | Val Acc: 0.9688
Epoch 02 | Train Acc: 0.9760 | Val Acc: 0.9780
Epoch 03 | Train Acc: 0.9811 | Val Acc: 0.9789
Epoch 04 | Train Acc: 0.9827 | Val Acc: 0.9801
Epoch 05 | Train Acc: 0.9845 | Val Acc: 0.9796
Epoch 06 | Train Acc: 0.9857 | Val Acc: 0.9824
Epoch 07 | Train Acc: 0.9865 | Val Acc: 0.9828
Epoch 08 | Train Acc: 0.9876 | Val Acc: 0.9822
Best Val Acc: 0.9828
Test Acc: 0.9827
Runtime (sec): 83.52
================================================================================
MNIST | CNN-simple | Config 5/9
{'lr': 0.001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.9308 | Val Acc: 0.9733
Epoch 02 | Train Acc: 0.9773 | Val Acc: 0.9758
Epoch 03 | Train Acc: 0.9815 | Val Acc: 0.9813
Epoch 04 | Train Acc: 0.9839 | Val Acc: 0.9800
Epoch 05 | Train Acc: 0.9850 | Val Acc: 0.9806
Early stopping triggered.
Best Val Acc: 0.9813
Test Acc: 0.9824
Runtime (sec): 42.13
================================================================================
MNIST | CNN-simple | Config 6/9
{'lr': 0.001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.9033 | Val Acc: 0.9676
Epoch 02 | Train Acc: 0.9733 | Val Acc: 0.9760
Epoch 03 | Train Acc: 0.9786 | Val Acc: 0.9767
Epoch 04 | Train Acc: 0.9812 | Val Acc: 0.9795
Epoch 05 | Train Acc: 0.9829 | Val Acc: 0.9820
Epoch 06 | Train Acc: 0.9834 | Val Acc: 0.9805
Epoch 07 | Train Acc: 0.9846 | Val Acc: 0.9816
Early stopping triggered.
Best Val Acc: 0.982
Test Acc: 0.9839
Runtime (sec): 50.93
================================================================================
MNIST | CNN-simple | Config 7/9
{'lr': 0.0001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.8001 | Val Acc: 0.9233
Epoch 02 | Train Acc: 0.9415 | Val Acc: 0.9492
Epoch 03 | Train Acc: 0.9571 | Val Acc: 0.9605
Epoch 04 | Train Acc: 0.9652 | Val Acc: 0.9642
Epoch 05 | Train Acc: 0.9700 | Val Acc: 0.9690
Epoch 06 | Train Acc: 0.9727 | Val Acc: 0.9716
Epoch 07 | Train Acc: 0.9761 | Val Acc: 0.9728
Epoch 08 | Train Acc: 0.9773 | Val Acc: 0.9742
Best Val Acc: 0.9742
Test Acc: 0.9779
Runtime (sec): 83.2
================================================================================
MNIST | CNN-simple | Config 8/9
{'lr': 0.0001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.7168 | Val Acc: 0.8809
Epoch 02 | Train Acc: 0.9094 | Val Acc: 0.9265
Epoch 03 | Train Acc: 0.9399 | Val Acc: 0.9453
Epoch 04 | Train Acc: 0.9544 | Val Acc: 0.9583
Epoch 05 | Train Acc: 0.9628 | Val Acc: 0.9649
Epoch 06 | Train Acc: 0.9681 | Val Acc: 0.9671
Epoch 07 | Train Acc: 0.9714 | Val Acc: 0.9699
Epoch 08 | Train Acc: 0.9737 | Val Acc: 0.9730
Best Val Acc: 0.973
Test Acc: 0.9746
Runtime (sec): 67.81
================================================================================
MNIST | CNN-simple | Config 9/9
{'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.6780 | Val Acc: 0.8669
Epoch 02 | Train Acc: 0.8978 | Val Acc: 0.9183
Epoch 03 | Train Acc: 0.9307 | Val Acc: 0.9407
Epoch 04 | Train Acc: 0.9450 | Val Acc: 0.9507
Epoch 05 | Train Acc: 0.9530 | Val Acc: 0.9572
Epoch 06 | Train Acc: 0.9589 | Val Acc: 0.9613
Epoch 07 | Train Acc: 0.9629 | Val Acc: 0.9652
Epoch 08 | Train Acc: 0.9656 | Val Acc: 0.9672
Best Val Acc: 0.9672
Test Acc: 0.9695
Runtime (sec): 58.42

In [41]:
mnist_simple_cnn_df

,dataset,architecture,lr,batch_size,weight_decay,best_val_acc,test_acc,runtime_sec
0,MNIST,simple,0.0100,32,0.0000,0.9834,0.9855,73.811355
1,MNIST,simple,0.0100,64,0.0001,0.9832,0.9802,58.606896
2,MNIST,simple,0.0010,32,0.0000,0.9828,0.9827,83.524770
3,MNIST,simple,0.0010,128,0.0050,0.9820,0.9839,50.927203
4,MNIST,simple,0.0010,64,0.0001,0.9813,0.9824,42.128740
5,MNIST,simple,0.0100,128,0.0050,0.9793,0.9738,57.508236
6,MNIST,simple,0.0001,32,0.0000,0.9742,0.9779,83.196182
7,MNIST,simple,0.0001,64,0.0001,0.9730,0.9746,67.807506
8,MNIST,simple,0.0001,128,0.0050,0.9672,0.9695,58.416486

In [42]:
mnist_simple_cnn_best

{'dataset': 'MNIST',
 'architecture': 'simple',
 'lr': 0.01,
 'batch_size': 32,
 'weight_decay': 0.0,
 'best_val_acc': 0.9834,
 'test_acc': 0.9855,
 'runtime_sec': 73.81135535240173}

In [43]:
mnist_enhanced_cnn_df, mnist_enhanced_cnn_best = tune_cnn_architecture(
    dataset_name="MNIST",
    architecture_name="enhanced",
    train_dataset=mnist_train,
    val_dataset=mnist_val,
    test_dataset=mnist_test,
    configs=cnn_configs,
    epochs=8,
    patience=2
)

================================================================================
MNIST | CNN-enhanced | Config 1/9
{'lr': 0.01, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.9575 | Val Acc: 0.9752
Epoch 02 | Train Acc: 0.9809 | Val Acc: 0.9785
Epoch 03 | Train Acc: 0.9844 | Val Acc: 0.9836
Epoch 04 | Train Acc: 0.9872 | Val Acc: 0.9867
Epoch 05 | Train Acc: 0.9876 | Val Acc: 0.9789
Epoch 06 | Train Acc: 0.9896 | Val Acc: 0.9824
Early stopping triggered.
Best Val Acc: 0.9867
Test Acc: 0.9848
Runtime (sec): 72.33
================================================================================
MNIST | CNN-enhanced | Config 2/9
{'lr': 0.01, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.9530 | Val Acc: 0.9772
Epoch 02 | Train Acc: 0.9818 | Val Acc: 0.9818
Epoch 03 | Train Acc: 0.9834 | Val Acc: 0.9806
Epoch 04 | Train Acc: 0.9847 | Val Acc: 0.9751
Early stopping triggered.
Best Val Acc: 0.9818
Test Acc: 0.9756
Runtime (sec): 36.65
================================================================================
MNIST | CNN-enhanced | Config 3/9
{'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.9357 | Val Acc: 0.9186
Epoch 02 | Train Acc: 0.9717 | Val Acc: 0.9587
Epoch 03 | Train Acc: 0.9738 | Val Acc: 0.9614
Epoch 04 | Train Acc: 0.9737 | Val Acc: 0.9706
Epoch 05 | Train Acc: 0.9752 | Val Acc: 0.9692
Epoch 06 | Train Acc: 0.9737 | Val Acc: 0.9735
Epoch 07 | Train Acc: 0.9749 | Val Acc: 0.9412
Epoch 08 | Train Acc: 0.9759 | Val Acc: 0.9739
Best Val Acc: 0.9739
Test Acc: 0.9794
Runtime (sec): 61.56
================================================================================
MNIST | CNN-enhanced | Config 4/9
{'lr': 0.001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.9658 | Val Acc: 0.9691
Epoch 02 | Train Acc: 0.9851 | Val Acc: 0.9849
Epoch 03 | Train Acc: 0.9883 | Val Acc: 0.9793
Epoch 04 | Train Acc: 0.9905 | Val Acc: 0.9872
Epoch 05 | Train Acc: 0.9926 | Val Acc: 0.9878
Epoch 06 | Train Acc: 0.9934 | Val Acc: 0.9769
Epoch 07 | Train Acc: 0.9951 | Val Acc: 0.9855
Early stopping triggered.
Best Val Acc: 0.9878
Test Acc: 0.9842
Runtime (sec): 83.06
================================================================================
MNIST | CNN-enhanced | Config 5/9
{'lr': 0.001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.9623 | Val Acc: 0.9841
Epoch 02 | Train Acc: 0.9862 | Val Acc: 0.9874
Epoch 03 | Train Acc: 0.9898 | Val Acc: 0.9851
Epoch 04 | Train Acc: 0.9918 | Val Acc: 0.9876
Epoch 05 | Train Acc: 0.9930 | Val Acc: 0.9840
Epoch 06 | Train Acc: 0.9935 | Val Acc: 0.9903
Epoch 07 | Train Acc: 0.9944 | Val Acc: 0.9906
Epoch 08 | Train Acc: 0.9946 | Val Acc: 0.9873
Best Val Acc: 0.9906
Test Acc: 0.991
Runtime (sec): 73.03
================================================================================
MNIST | CNN-enhanced | Config 6/9
{'lr': 0.001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.9545 | Val Acc: 0.9833
Epoch 02 | Train Acc: 0.9854 | Val Acc: 0.9844
Epoch 03 | Train Acc: 0.9872 | Val Acc: 0.9855
Epoch 04 | Train Acc: 0.9885 | Val Acc: 0.9850
Epoch 05 | Train Acc: 0.9889 | Val Acc: 0.9875
Epoch 06 | Train Acc: 0.9903 | Val Acc: 0.9786
Epoch 07 | Train Acc: 0.9904 | Val Acc: 0.9815
Early stopping triggered.
Best Val Acc: 0.9875
Test Acc: 0.9812
Runtime (sec): 53.93
================================================================================
MNIST | CNN-enhanced | Config 7/9
{'lr': 0.0001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.9315 | Val Acc: 0.9763
Epoch 02 | Train Acc: 0.9821 | Val Acc: 0.9832
Epoch 03 | Train Acc: 0.9876 | Val Acc: 0.9856
Epoch 04 | Train Acc: 0.9908 | Val Acc: 0.9877
Epoch 05 | Train Acc: 0.9928 | Val Acc: 0.9863
Epoch 06 | Train Acc: 0.9944 | Val Acc: 0.9896
Epoch 07 | Train Acc: 0.9954 | Val Acc: 0.9880
Epoch 08 | Train Acc: 0.9962 | Val Acc: 0.9880
Early stopping triggered.
Best Val Acc: 0.9896
Test Acc: 0.9887
Runtime (sec): 95.17
================================================================================
MNIST | CNN-enhanced | Config 8/9
{'lr': 0.0001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.9132 | Val Acc: 0.9710
Epoch 02 | Train Acc: 0.9789 | Val Acc: 0.9805
Epoch 03 | Train Acc: 0.9855 | Val Acc: 0.9835
Epoch 04 | Train Acc: 0.9890 | Val Acc: 0.9846
Epoch 05 | Train Acc: 0.9909 | Val Acc: 0.9877
Epoch 06 | Train Acc: 0.9925 | Val Acc: 0.9869
Epoch 07 | Train Acc: 0.9944 | Val Acc: 0.9893
Epoch 08 | Train Acc: 0.9956 | Val Acc: 0.9872
Best Val Acc: 0.9893
Test Acc: 0.9911
Runtime (sec): 74.38
================================================================================
MNIST | CNN-enhanced | Config 9/9
{'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.8825 | Val Acc: 0.9630
Epoch 02 | Train Acc: 0.9741 | Val Acc: 0.9765
Epoch 03 | Train Acc: 0.9818 | Val Acc: 0.9806
Epoch 04 | Train Acc: 0.9850 | Val Acc: 0.9813
Epoch 05 | Train Acc: 0.9872 | Val Acc: 0.9838
Epoch 06 | Train Acc: 0.9888 | Val Acc: 0.9872
Epoch 07 | Train Acc: 0.9900 | Val Acc: 0.9860
Epoch 08 | Train Acc: 0.9913 | Val Acc: 0.9872
Early stopping triggered.
Best Val Acc: 0.9872
Test Acc: 0.9873
Runtime (sec): 62.28

In [44]:
cifar_simple_cnn_df, cifar_simple_cnn_best = tune_cnn_architecture(
    dataset_name="CIFAR10",
    architecture_name="simple",
    train_dataset=cifar_train,
    val_dataset=cifar_val,
    test_dataset=cifar_test,
    configs=cnn_configs,
    epochs=10,
    patience=2
)

================================================================================
CIFAR10 | CNN-simple | Config 1/9
{'lr': 0.01, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.4753 | Val Acc: 0.5284
Epoch 02 | Train Acc: 0.5561 | Val Acc: 0.5650
Epoch 03 | Train Acc: 0.5763 | Val Acc: 0.5226
Epoch 04 | Train Acc: 0.5883 | Val Acc: 0.5892
Epoch 05 | Train Acc: 0.5986 | Val Acc: 0.5586
Epoch 06 | Train Acc: 0.6018 | Val Acc: 0.5892
Early stopping triggered.
Best Val Acc: 0.5892
Test Acc: 0.601
Runtime (sec): 62.78
================================================================================
CIFAR10 | CNN-simple | Config 2/9
{'lr': 0.01, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.4630 | Val Acc: 0.4666
Epoch 02 | Train Acc: 0.5595 | Val Acc: 0.5174
Epoch 03 | Train Acc: 0.5899 | Val Acc: 0.5216
Epoch 04 | Train Acc: 0.6058 | Val Acc: 0.5736
Epoch 05 | Train Acc: 0.6125 | Val Acc: 0.5842
Epoch 06 | Train Acc: 0.6174 | Val Acc: 0.5852
Epoch 07 | Train Acc: 0.6220 | Val Acc: 0.5726
Epoch 08 | Train Acc: 0.6208 | Val Acc: 0.5746
Early stopping triggered.
Best Val Acc: 0.5852
Test Acc: 0.5767
Runtime (sec): 68.59
================================================================================
CIFAR10 | CNN-simple | Config 3/9
{'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.4505 | Val Acc: 0.4376
Epoch 02 | Train Acc: 0.5428 | Val Acc: 0.5230
Epoch 03 | Train Acc: 0.5609 | Val Acc: 0.5066
Epoch 04 | Train Acc: 0.5720 | Val Acc: 0.4862
Early stopping triggered.
Best Val Acc: 0.523
Test Acc: 0.4898
Runtime (sec): 30.08
================================================================================
CIFAR10 | CNN-simple | Config 4/9
{'lr': 0.001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.4736 | Val Acc: 0.4894
Epoch 02 | Train Acc: 0.5648 | Val Acc: 0.5898
Epoch 03 | Train Acc: 0.5940 | Val Acc: 0.5758
Epoch 04 | Train Acc: 0.6077 | Val Acc: 0.5834
Early stopping triggered.
Best Val Acc: 0.5898
Test Acc: 0.5746
Runtime (sec): 40.58
================================================================================
CIFAR10 | CNN-simple | Config 5/9
{'lr': 0.001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.4494 | Val Acc: 0.5096
Epoch 02 | Train Acc: 0.5550 | Val Acc: 0.5170
Epoch 03 | Train Acc: 0.5881 | Val Acc: 0.5428
Epoch 04 | Train Acc: 0.6069 | Val Acc: 0.5548
Epoch 05 | Train Acc: 0.6157 | Val Acc: 0.6106
Epoch 06 | Train Acc: 0.6277 | Val Acc: 0.5988
Epoch 07 | Train Acc: 0.6287 | Val Acc: 0.5744
Early stopping triggered.
Best Val Acc: 0.6106
Test Acc: 0.5741
Runtime (sec): 59.11
================================================================================
CIFAR10 | CNN-simple | Config 6/9
{'lr': 0.001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.4396 | Val Acc: 0.5172
Epoch 02 | Train Acc: 0.5596 | Val Acc: 0.5156
Epoch 03 | Train Acc: 0.5941 | Val Acc: 0.5792
Epoch 04 | Train Acc: 0.6114 | Val Acc: 0.5438
Epoch 05 | Train Acc: 0.6191 | Val Acc: 0.6098
Epoch 06 | Train Acc: 0.6317 | Val Acc: 0.6142
Epoch 07 | Train Acc: 0.6366 | Val Acc: 0.5760
Epoch 08 | Train Acc: 0.6411 | Val Acc: 0.6100
Early stopping triggered.
Best Val Acc: 0.6142
Test Acc: 0.6058
Runtime (sec): 59.43
================================================================================
CIFAR10 | CNN-simple | Config 7/9
{'lr': 0.0001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.3365 | Val Acc: 0.4180
Epoch 02 | Train Acc: 0.4539 | Val Acc: 0.4720
Epoch 03 | Train Acc: 0.4929 | Val Acc: 0.5146
Epoch 04 | Train Acc: 0.5221 | Val Acc: 0.5280
Epoch 05 | Train Acc: 0.5395 | Val Acc: 0.5470
Epoch 06 | Train Acc: 0.5547 | Val Acc: 0.5548
Epoch 07 | Train Acc: 0.5644 | Val Acc: 0.5538
Epoch 08 | Train Acc: 0.5721 | Val Acc: 0.5598
Epoch 09 | Train Acc: 0.5775 | Val Acc: 0.5714
Epoch 10 | Train Acc: 0.5852 | Val Acc: 0.5764
Best Val Acc: 0.5764
Test Acc: 0.5724
Runtime (sec): 101.96
================================================================================
CIFAR10 | CNN-simple | Config 8/9
{'lr': 0.0001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.3235 | Val Acc: 0.4002
Epoch 02 | Train Acc: 0.4344 | Val Acc: 0.4584
Epoch 03 | Train Acc: 0.4840 | Val Acc: 0.4996
Epoch 04 | Train Acc: 0.5119 | Val Acc: 0.5212
Epoch 05 | Train Acc: 0.5307 | Val Acc: 0.5272
Epoch 06 | Train Acc: 0.5432 | Val Acc: 0.5490
Epoch 07 | Train Acc: 0.5568 | Val Acc: 0.5466
Epoch 08 | Train Acc: 0.5640 | Val Acc: 0.5582
Epoch 09 | Train Acc: 0.5726 | Val Acc: 0.5680
Epoch 10 | Train Acc: 0.5781 | Val Acc: 0.5764
Best Val Acc: 0.5764
Test Acc: 0.568
Runtime (sec): 84.1
================================================================================
CIFAR10 | CNN-simple | Config 9/9
{'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.2750 | Val Acc: 0.3842
Epoch 02 | Train Acc: 0.4142 | Val Acc: 0.4522
Epoch 03 | Train Acc: 0.4638 | Val Acc: 0.4804
Epoch 04 | Train Acc: 0.4963 | Val Acc: 0.5100
Epoch 05 | Train Acc: 0.5175 | Val Acc: 0.5226
Epoch 06 | Train Acc: 0.5312 | Val Acc: 0.5284
Epoch 07 | Train Acc: 0.5427 | Val Acc: 0.5390
Epoch 08 | Train Acc: 0.5510 | Val Acc: 0.5416
Epoch 09 | Train Acc: 0.5582 | Val Acc: 0.5530
Epoch 10 | Train Acc: 0.5634 | Val Acc: 0.5600
Best Val Acc: 0.56
Test Acc: 0.5543
Runtime (sec): 74.52

In [45]:
cifar_enhanced_cnn_df, cifar_enhanced_cnn_best = tune_cnn_architecture(
    dataset_name="CIFAR10",
    architecture_name="enhanced",
    train_dataset=cifar_train,
    val_dataset=cifar_val,
    test_dataset=cifar_test,
    configs=cnn_configs,
    epochs=10,
    patience=2
)

================================================================================
CIFAR10 | CNN-enhanced | Config 1/9
{'lr': 0.01, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.4256 | Val Acc: 0.4956
Epoch 02 | Train Acc: 0.5780 | Val Acc: 0.5248
Epoch 03 | Train Acc: 0.6321 | Val Acc: 0.5748
Epoch 04 | Train Acc: 0.6663 | Val Acc: 0.6192
Epoch 05 | Train Acc: 0.6907 | Val Acc: 0.6814
Epoch 06 | Train Acc: 0.7090 | Val Acc: 0.6416
Epoch 07 | Train Acc: 0.7229 | Val Acc: 0.6616
Early stopping triggered.
Best Val Acc: 0.6814
Test Acc: 0.6589
Runtime (sec): 81.14
================================================================================
CIFAR10 | CNN-enhanced | Config 2/9
{'lr': 0.01, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.4680 | Val Acc: 0.4420
Epoch 02 | Train Acc: 0.6269 | Val Acc: 0.4938
Epoch 03 | Train Acc: 0.6761 | Val Acc: 0.6230
Epoch 04 | Train Acc: 0.7068 | Val Acc: 0.6708
Epoch 05 | Train Acc: 0.7178 | Val Acc: 0.6252
Epoch 06 | Train Acc: 0.7325 | Val Acc: 0.6264
Early stopping triggered.
Best Val Acc: 0.6708
Test Acc: 0.6171
Runtime (sec): 54.69
================================================================================
CIFAR10 | CNN-enhanced | Config 3/9
{'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.4126 | Val Acc: 0.4648
Epoch 02 | Train Acc: 0.5687 | Val Acc: 0.5352
Epoch 03 | Train Acc: 0.6002 | Val Acc: 0.5252
Epoch 04 | Train Acc: 0.6137 | Val Acc: 0.4408
Early stopping triggered.
Best Val Acc: 0.5352
Test Acc: 0.4406
Runtime (sec): 31.1
================================================================================
CIFAR10 | CNN-enhanced | Config 4/9
{'lr': 0.001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.5515 | Val Acc: 0.5906
Epoch 02 | Train Acc: 0.6766 | Val Acc: 0.5948
Epoch 03 | Train Acc: 0.7198 | Val Acc: 0.6648
Epoch 04 | Train Acc: 0.7517 | Val Acc: 0.7158
Epoch 05 | Train Acc: 0.7760 | Val Acc: 0.7152
Epoch 06 | Train Acc: 0.7953 | Val Acc: 0.7302
Epoch 07 | Train Acc: 0.8146 | Val Acc: 0.7178
Epoch 08 | Train Acc: 0.8291 | Val Acc: 0.6806
Early stopping triggered.
Best Val Acc: 0.7302
Test Acc: 0.6753
Runtime (sec): 92.05
================================================================================
CIFAR10 | CNN-enhanced | Config 5/9
{'lr': 0.001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.5395 | Val Acc: 0.5458
Epoch 02 | Train Acc: 0.6708 | Val Acc: 0.6870
Epoch 03 | Train Acc: 0.7146 | Val Acc: 0.6766
Epoch 04 | Train Acc: 0.7422 | Val Acc: 0.6940
Epoch 05 | Train Acc: 0.7686 | Val Acc: 0.6976
Epoch 06 | Train Acc: 0.7844 | Val Acc: 0.7150
Epoch 07 | Train Acc: 0.8025 | Val Acc: 0.7220
Epoch 08 | Train Acc: 0.8140 | Val Acc: 0.7394
Epoch 09 | Train Acc: 0.8261 | Val Acc: 0.6920
Epoch 10 | Train Acc: 0.8361 | Val Acc: 0.7018
Early stopping triggered.
Best Val Acc: 0.7394
Test Acc: 0.7034
Runtime (sec): 91.23
================================================================================
CIFAR10 | CNN-enhanced | Config 6/9
{'lr': 0.001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.5222 | Val Acc: 0.5352
Epoch 02 | Train Acc: 0.6455 | Val Acc: 0.6506
Epoch 03 | Train Acc: 0.6900 | Val Acc: 0.6484
Epoch 04 | Train Acc: 0.7148 | Val Acc: 0.6670
Epoch 05 | Train Acc: 0.7311 | Val Acc: 0.6926
Epoch 06 | Train Acc: 0.7471 | Val Acc: 0.7108
Epoch 07 | Train Acc: 0.7540 | Val Acc: 0.6914
Epoch 08 | Train Acc: 0.7645 | Val Acc: 0.6960
Early stopping triggered.
Best Val Acc: 0.7108
Test Acc: 0.687
Runtime (sec): 62.41
================================================================================
CIFAR10 | CNN-enhanced | Config 7/9
{'lr': 0.0001, 'batch_size': 32, 'weight_decay': 0.0}
Epoch 01 | Train Acc: 0.4689 | Val Acc: 0.5620
Epoch 02 | Train Acc: 0.6049 | Val Acc: 0.6270
Epoch 03 | Train Acc: 0.6497 | Val Acc: 0.6394
Epoch 04 | Train Acc: 0.6767 | Val Acc: 0.6642
Epoch 05 | Train Acc: 0.6974 | Val Acc: 0.6758
Epoch 06 | Train Acc: 0.7122 | Val Acc: 0.6838
Epoch 07 | Train Acc: 0.7278 | Val Acc: 0.6780
Epoch 08 | Train Acc: 0.7401 | Val Acc: 0.6906
Epoch 09 | Train Acc: 0.7519 | Val Acc: 0.6894
Epoch 10 | Train Acc: 0.7610 | Val Acc: 0.7048
Best Val Acc: 0.7048
Test Acc: 0.7175
Runtime (sec): 114.88
================================================================================
CIFAR10 | CNN-enhanced | Config 8/9
{'lr': 0.0001, 'batch_size': 64, 'weight_decay': 0.0001}
Epoch 01 | Train Acc: 0.4468 | Val Acc: 0.5240
Epoch 02 | Train Acc: 0.5736 | Val Acc: 0.5944
Epoch 03 | Train Acc: 0.6243 | Val Acc: 0.6284
Epoch 04 | Train Acc: 0.6555 | Val Acc: 0.6498
Epoch 05 | Train Acc: 0.6772 | Val Acc: 0.6606
Epoch 06 | Train Acc: 0.6928 | Val Acc: 0.6656
Epoch 07 | Train Acc: 0.7082 | Val Acc: 0.6790
Epoch 08 | Train Acc: 0.7203 | Val Acc: 0.6834
Epoch 09 | Train Acc: 0.7312 | Val Acc: 0.6910
Epoch 10 | Train Acc: 0.7412 | Val Acc: 0.6894
Best Val Acc: 0.691
Test Acc: 0.6895
Runtime (sec): 91.21
================================================================================
CIFAR10 | CNN-enhanced | Config 9/9
{'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.005}
Epoch 01 | Train Acc: 0.4108 | Val Acc: 0.4930
Epoch 02 | Train Acc: 0.5403 | Val Acc: 0.5602
Epoch 03 | Train Acc: 0.5916 | Val Acc: 0.6024
Epoch 04 | Train Acc: 0.6216 | Val Acc: 0.6208
Epoch 05 | Train Acc: 0.6457 | Val Acc: 0.6404
Epoch 06 | Train Acc: 0.6604 | Val Acc: 0.6546
Epoch 07 | Train Acc: 0.6753 | Val Acc: 0.6622
Epoch 08 | Train Acc: 0.6884 | Val Acc: 0.6586
Epoch 09 | Train Acc: 0.6983 | Val Acc: 0.6652
Epoch 10 | Train Acc: 0.7073 | Val Acc: 0.6804
Best Val Acc: 0.6804
Test Acc: 0.6822
Runtime (sec): 77.9

In [46]:
mnist_simple_cnn_df.to_csv("mnist_simple_cnn_tuning.csv", index=False)
mnist_enhanced_cnn_df.to_csv("mnist_enhanced_cnn_tuning.csv", index=False)
cifar_simple_cnn_df.to_csv("cifar_simple_cnn_tuning.csv", index=False)
cifar_enhanced_cnn_df.to_csv("cifar_enhanced_cnn_tuning.csv", index=False)

mnist_cnn_best_df = pd.DataFrame([mnist_simple_cnn_best, mnist_enhanced_cnn_best])
cifar_cnn_best_df = pd.DataFrame([cifar_simple_cnn_best, cifar_enhanced_cnn_best])

mnist_cnn_best_df.to_csv("mnist_cnn_best_results.csv", index=False)
cifar_cnn_best_df.to_csv("cifar_cnn_best_results.csv", index=False)

In [47]:
mnist_trainval = ConcatDataset([mnist_train, mnist_val])
cifar_trainval = ConcatDataset([cifar_train, cifar_val])

print("MNIST train+val size:", len(mnist_trainval))
print("CIFAR train+val size:", len(cifar_trainval))

MNIST train+val size: 60000
CIFAR train+val size: 50000

In [48]:
def make_final_loaders(trainval_dataset, test_dataset, batch_size):
    trainval_loader = DataLoader(trainval_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return trainval_loader, test_loader

In [49]:
def train_full_model(model, train_loader, criterion, optimizer, device, epochs=10):
    history = []
    start_time = time.time()

    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "train_acc": train_acc
        })
        print(f"Epoch {epoch:02d} | Train Acc: {train_acc:.4f}")

    runtime = time.time() - start_time
    return model, runtime, history

In [50]:
def retrain_best_mlp(row, trainval_dataset, test_dataset, epochs=10):
    dataset_name = row["dataset"]
    architecture_name = row["architecture"]

    input_size = 784 if dataset_name == "MNIST" else 3072
    hidden_layers = MLP_ARCHITECTURES[architecture_name]
    batch_size = int(row["batch_size"])
    lr = float(row["lr"])
    optimizer_name = row["optimizer"]
    dropout = float(row["dropout"])

    train_loader, test_loader = make_final_loaders(trainval_dataset, test_dataset, batch_size)

    model = MLP(
        input_size=input_size,
        hidden_layers=hidden_layers,
        dropout=dropout
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = get_optimizer(optimizer_name, model, lr=lr)

    model, runtime, history = train_full_model(
        model, train_loader, criterion, optimizer, device, epochs=epochs
    )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    result = {
        "dataset": dataset_name,
        "architecture": architecture_name,
        "hidden_layers": str(hidden_layers),
        "lr": lr,
        "batch_size": batch_size,
        "optimizer": optimizer_name,
        "dropout": dropout,
        "final_test_acc": test_acc,
        "runtime_sec": runtime
    }

    return result, history

In [51]:
final_mlp_results = []

all_mlp_best_df = pd.concat([mnist_mlp_best_df, cifar_mlp_best_df], ignore_index=True)

for _, row in all_mlp_best_df.iterrows():
    dataset_name = row["dataset"]

    if dataset_name == "MNIST":
        trainval_dataset = mnist_trainval
        test_dataset = mnist_test
        epochs = 10
    else:
        trainval_dataset = cifar_trainval
        test_dataset = cifar_test
        epochs = 15

    print("=" * 80)
    print(f"Final retrain MLP | {dataset_name} | {row['architecture']}")

    result, history = retrain_best_mlp(
        row=row,
        trainval_dataset=trainval_dataset,
        test_dataset=test_dataset,
        epochs=epochs
    )

    final_mlp_results.append(result)

final_mlp_retrained_df = pd.DataFrame(final_mlp_results)
final_mlp_retrained_df

================================================================================
Final retrain MLP | MNIST | shallow
Epoch 01 | Train Acc: 0.9085
Epoch 02 | Train Acc: 0.9526
Epoch 03 | Train Acc: 0.9654
Epoch 04 | Train Acc: 0.9700
Epoch 05 | Train Acc: 0.9742
Epoch 06 | Train Acc: 0.9774
Epoch 07 | Train Acc: 0.9800
Epoch 08 | Train Acc: 0.9816
Epoch 09 | Train Acc: 0.9833
Epoch 10 | Train Acc: 0.9847
================================================================================
Final retrain MLP | MNIST | medium
Epoch 01 | Train Acc: 0.9091
Epoch 02 | Train Acc: 0.9632
Epoch 03 | Train Acc: 0.9728
Epoch 04 | Train Acc: 0.9781
Epoch 05 | Train Acc: 0.9815
Epoch 06 | Train Acc: 0.9830
Epoch 07 | Train Acc: 0.9857
Epoch 08 | Train Acc: 0.9869
Epoch 09 | Train Acc: 0.9884
Epoch 10 | Train Acc: 0.9893
================================================================================
Final retrain MLP | MNIST | deep
Epoch 01 | Train Acc: 0.8959
Epoch 02 | Train Acc: 0.9634
Epoch 03 | Train Acc: 0.9714
Epoch 04 | Train Acc: 0.9776
Epoch 05 | Train Acc: 0.9812
Epoch 06 | Train Acc: 0.9831
Epoch 07 | Train Acc: 0.9841
Epoch 08 | Train Acc: 0.9866
Epoch 09 | Train Acc: 0.9871
Epoch 10 | Train Acc: 0.9880
================================================================================
Final retrain MLP | CIFAR10 | shallow
Epoch 01 | Train Acc: 0.2993
Epoch 02 | Train Acc: 0.3548
Epoch 03 | Train Acc: 0.3671
Epoch 04 | Train Acc: 0.3815
Epoch 05 | Train Acc: 0.3888
Epoch 06 | Train Acc: 0.3981
Epoch 07 | Train Acc: 0.4064
Epoch 08 | Train Acc: 0.4075
Epoch 09 | Train Acc: 0.4083
Epoch 10 | Train Acc: 0.4144
Epoch 11 | Train Acc: 0.4186
Epoch 12 | Train Acc: 0.4207
Epoch 13 | Train Acc: 0.4241
Epoch 14 | Train Acc: 0.4212
Epoch 15 | Train Acc: 0.4273
================================================================================
Final retrain MLP | CIFAR10 | medium
Epoch 01 | Train Acc: 0.2591
Epoch 02 | Train Acc: 0.3432
Epoch 03 | Train Acc: 0.3758
Epoch 04 | Train Acc: 0.3933
Epoch 05 | Train Acc: 0.4116
Epoch 06 | Train Acc: 0.4278
Epoch 07 | Train Acc: 0.4395
Epoch 08 | Train Acc: 0.4500
Epoch 09 | Train Acc: 0.4571
Epoch 10 | Train Acc: 0.4658
Epoch 11 | Train Acc: 0.4717
Epoch 12 | Train Acc: 0.4797
Epoch 13 | Train Acc: 0.4867
Epoch 14 | Train Acc: 0.4894
Epoch 15 | Train Acc: 0.4954
================================================================================
Final retrain MLP | CIFAR10 | deep
Epoch 01 | Train Acc: 0.2082
Epoch 02 | Train Acc: 0.2926
Epoch 03 | Train Acc: 0.3364
Epoch 04 | Train Acc: 0.3649
Epoch 05 | Train Acc: 0.3896
Epoch 06 | Train Acc: 0.4078
Epoch 07 | Train Acc: 0.4187
Epoch 08 | Train Acc: 0.4315
Epoch 09 | Train Acc: 0.4431
Epoch 10 | Train Acc: 0.4498
Epoch 11 | Train Acc: 0.4581
Epoch 12 | Train Acc: 0.4655
Epoch 13 | Train Acc: 0.4734
Epoch 14 | Train Acc: 0.4822
Epoch 15 | Train Acc: 0.4881

,dataset,architecture,hidden_layers,lr,batch_size,optimizer,dropout,final_test_acc,runtime_sec
0,MNIST,shallow,[128],0.0010,32,Adam,0.2,0.9803,101.754460
1,MNIST,medium,"[512, 256, 128]",0.0010,64,Adam,0.2,0.9836,88.885520
2,MNIST,deep,"[1024, 512, 256, 128, 64]",0.0010,64,Adam,0.2,0.9821,94.928338
3,CIFAR10,shallow,[128],0.0010,128,Adam,0.2,0.4381,111.700300
4,CIFAR10,medium,"[512, 256, 128]",0.0001,64,Adam,0.2,0.5036,130.750005
5,CIFAR10,deep,"[1024, 512, 256, 128, 64]",0.0001,64,Adam,0.2,0.5019,138.523438

In [52]:
final_mlp_retrained_df.to_csv("final_mlp_retrained_results.csv", index=False)
print("Saved final_mlp_retrained_results.csv")

Saved final_mlp_retrained_results.csv

In [53]:
def retrain_best_cnn(row, trainval_dataset, test_dataset, epochs=10):
    dataset_name = row["dataset"]
    architecture_name = row["architecture"]

    in_channels = 1 if dataset_name == "MNIST" else 3
    batch_size = int(row["batch_size"])
    lr = float(row["lr"])
    weight_decay = float(row["weight_decay"])

    train_loader, test_loader = make_final_loaders(trainval_dataset, test_dataset, batch_size)

    if architecture_name == "simple":
        model = SimpleCNN(in_channels=in_channels).to(device)
    elif architecture_name == "enhanced":
        model = EnhancedCNN(in_channels=in_channels).to(device)
    else:
        raise ValueError("Unknown CNN architecture")

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    model, runtime, history = train_full_model(
        model, train_loader, criterion, optimizer, device, epochs=epochs
    )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    result = {
        "dataset": dataset_name,
        "architecture": architecture_name,
        "lr": lr,
        "batch_size": batch_size,
        "weight_decay": weight_decay,
        "final_test_acc": test_acc,
        "runtime_sec": runtime
    }

    return result, history

In [54]:
final_cnn_results = []

all_cnn_best_df = pd.concat([mnist_cnn_best_df, cifar_cnn_best_df], ignore_index=True)

for _, row in all_cnn_best_df.iterrows():
    dataset_name = row["dataset"]

    if dataset_name == "MNIST":
        trainval_dataset = mnist_trainval
        test_dataset = mnist_test
        epochs = 10
    else:
        trainval_dataset = cifar_trainval
        test_dataset = cifar_test
        epochs = 15

    print("=" * 80)
    print(f"Final retrain CNN | {dataset_name} | {row['architecture']}")

    result, history = retrain_best_cnn(
        row=row,
        trainval_dataset=trainval_dataset,
        test_dataset=test_dataset,
        epochs=epochs
    )

    final_cnn_results.append(result)

final_cnn_retrained_df = pd.DataFrame(final_cnn_results)
final_cnn_retrained_df

================================================================================
Final retrain CNN | MNIST | simple
Epoch 01 | Train Acc: 0.9595
Epoch 02 | Train Acc: 0.9781
Epoch 03 | Train Acc: 0.9815
Epoch 04 | Train Acc: 0.9833
Epoch 05 | Train Acc: 0.9853
Epoch 06 | Train Acc: 0.9857
Epoch 07 | Train Acc: 0.9867
Epoch 08 | Train Acc: 0.9873
Epoch 09 | Train Acc: 0.9879
Epoch 10 | Train Acc: 0.9880
================================================================================
Final retrain CNN | MNIST | enhanced
Epoch 01 | Train Acc: 0.9643
Epoch 02 | Train Acc: 0.9861
Epoch 03 | Train Acc: 0.9896
Epoch 04 | Train Acc: 0.9917
Epoch 05 | Train Acc: 0.9933
Epoch 06 | Train Acc: 0.9939
Epoch 07 | Train Acc: 0.9948
Epoch 08 | Train Acc: 0.9952
Epoch 09 | Train Acc: 0.9957
Epoch 10 | Train Acc: 0.9953
================================================================================
Final retrain CNN | CIFAR10 | simple
Epoch 01 | Train Acc: 0.4426
Epoch 02 | Train Acc: 0.5438
Epoch 03 | Train Acc: 0.5716
Epoch 04 | Train Acc: 0.5861
Epoch 05 | Train Acc: 0.5982
Epoch 06 | Train Acc: 0.6073
Epoch 07 | Train Acc: 0.6127
Epoch 08 | Train Acc: 0.6195
Epoch 09 | Train Acc: 0.6214
Epoch 10 | Train Acc: 0.6243
Epoch 11 | Train Acc: 0.6278
Epoch 12 | Train Acc: 0.6296
Epoch 13 | Train Acc: 0.6285
Epoch 14 | Train Acc: 0.6344
Epoch 15 | Train Acc: 0.6371
================================================================================
Final retrain CNN | CIFAR10 | enhanced
Epoch 01 | Train Acc: 0.5478
Epoch 02 | Train Acc: 0.6824
Epoch 03 | Train Acc: 0.7273
Epoch 04 | Train Acc: 0.7565
Epoch 05 | Train Acc: 0.7801
Epoch 06 | Train Acc: 0.7992
Epoch 07 | Train Acc: 0.8179
Epoch 08 | Train Acc: 0.8338
Epoch 09 | Train Acc: 0.8443
Epoch 10 | Train Acc: 0.8589
Epoch 11 | Train Acc: 0.8697
Epoch 12 | Train Acc: 0.8806
Epoch 13 | Train Acc: 0.8918
Epoch 14 | Train Acc: 0.8996
Epoch 15 | Train Acc: 0.9073

,dataset,architecture,lr,batch_size,weight_decay,final_test_acc,runtime_sec
0,MNIST,simple,0.010,32,0.0000,0.9832,115.074626
1,MNIST,enhanced,0.001,64,0.0001,0.9894,100.358321
2,CIFAR10,simple,0.001,128,0.0050,0.6158,119.689862
3,CIFAR10,enhanced,0.001,64,0.0001,0.7440,147.724979

In [55]:
final_cnn_retrained_df.to_csv("final_cnn_retrained_results.csv", index=False)
print("Saved final_cnn_retrained_results.csv")

Saved final_cnn_retrained_results.csv

In [56]:
all_final_results_df = pd.concat(
    [final_mlp_retrained_df, final_cnn_retrained_df],
    ignore_index=True,
    sort=False
)

all_final_results_df.to_csv("all_final_results.csv", index=False)
all_final_results_df

,dataset,architecture,hidden_layers,lr,batch_size,optimizer,dropout,final_test_acc,runtime_sec,weight_decay
0,MNIST,shallow,[128],0.0010,32,Adam,0.2,0.9803,101.754460,NaN
1,MNIST,medium,"[512, 256, 128]",0.0010,64,Adam,0.2,0.9836,88.885520,NaN
2,MNIST,deep,"[1024, 512, 256, 128, 64]",0.0010,64,Adam,0.2,0.9821,94.928338,NaN
3,CIFAR10,shallow,[128],0.0010,128,Adam,0.2,0.4381,111.700300,NaN
4,CIFAR10,medium,"[512, 256, 128]",0.0001,64,Adam,0.2,0.5036,130.750005,NaN
5,CIFAR10,deep,"[1024, 512, 256, 128, 64]",0.0001,64,Adam,0.2,0.5019,138.523438,NaN
6,MNIST,simple,NaN,0.0100,32,NaN,NaN,0.9832,115.074626,0.0000
7,MNIST,enhanced,NaN,0.0010,64,NaN,NaN,0.9894,100.358321,0.0001
8,CIFAR10,simple,NaN,0.0010,128,NaN,NaN,0.6158,119.689862,0.0050
9,CIFAR10,enhanced,NaN,0.0010,64,NaN,NaN,0.7440,147.724979,0.0001